/**
 * Artifact Registry — Generated File Storage
 *
 * Stores metadata for files generated by agents and users:
 * - Financial reports (P&L, Balance Sheet, Cash Flow)
 * - Data exports (CSV, Excel, PDF)
 * - Generated invoices and credit notes
 * - Tax filings and compliance documents
 * - Custom reports
 *
 * The actual file content lives in R2. This table tracks:
 * - What was generated (kind, name, mimeType)
 * - Where it lives (r2Key, r2Bucket)
 * - Who generated it (createdBy — user or agent)
 * - Lifecycle (ttl, expiresAt, status)
 * - Audit trail (entityId, createdAt)
 */

import {
  pgTable,
  uuid,
  text,
  integer,
  timestamp,
  jsonb,
  boolean,
  pgEnum,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { uuidId, entityId, timestamps } from "./helpers";
import { entities } from "./organization";
import { users } from "./auth";

// ─── ENUMS ──────────────────────────────────────────────────────────────────

/** What kind of artifact was generated */
export const artifactKindEnum = pgEnum("artifact_kind", [
  "report", // Financial reports (P&L, Balance Sheet, Cash Flow, Trial Balance)
  "export", // Data exports (CSV, Excel, PDF of table data)
  "invoice_pdf", // Generated invoice PDFs
  "credit_note", // Generated credit notes
  "filing", // Tax filings and compliance documents
  "statement", // Bank statements, account statements
  "contract", // Generated contracts or agreements
  "custom", // User/agent-generated custom files
]);

/** Lifecycle status of the artifact */
export const artifactStatusEnum = pgEnum("artifact_status", [
  "generating", // File is being created (async generation)
  "ready", // File is ready for download
  "expired", // File has passed its TTL
  "failed", // Generation failed
  "archived", // Moved to long-term storage
]);

// ─── ARTIFACT REGISTRY ──────────────────────────────────────────────────────

export const artifactRegistry = pgTable(
  "artifact_registry",
  {
    id: uuidId(),
    entityId: entityId.references(() => entities.id, { onDelete: "cascade" }),

    // ── What ──
    kind: artifactKindEnum("kind").notNull(),
    name: text("name").notNull(), // Display name: "P&L Report - June 2026"
    description: text("description"), // Optional description
    mimeType: text("mime_type").notNull(), // e.g. "application/pdf", "text/csv"
    sizeBytes: integer("size_bytes"), // File size in bytes

    // ── Where ──
    r2Key: text("r2_key").notNull(), // R2 storage path
    r2Bucket: text("r2_bucket").notNull(), // R2 bucket name

    // ── Who ──
    createdBy: uuid("created_by").references(() => users.id), // User who triggered generation
    createdByName: text("created_by_name"), // Denormalized name for display
    agentName: text("agent_name"), // Agent that generated it (if agent-generated)

    // ── Source Reference ──
    /** Optional link to the source document that triggered this artifact */
    sourceDocumentId: uuid("source_document_id"),
    /** Optional link to the journal entry this artifact relates to */
    sourceJournalEntryId: uuid("source_journal_entry_id"),
    /** Optional link to the report configuration */
    reportConfigId: uuid("report_config_id"),

    // ── Parameters ──
    /** The parameters used to generate this artifact (for reproducibility) */
    parameters: jsonb("parameters")
      .$type<Record<string, unknown>>()
      .default({}),

    // ── Lifecycle ──
    status: artifactStatusEnum("status").notNull().default("generating"),
    /** Time-to-live in seconds. Null = never expires. */
    ttl: integer("ttl"),
    /** Computed expiration timestamp */
    expiresAt: timestamp("expires_at"),
    /** Whether the artifact should be pinned (never auto-deleted) */
    pinned: boolean("pinned").notNull().default(false),

    // ── Metadata ──
    metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}),

    ...timestamps,
  },
  (t) => [
    index("artifact_entity").on(t.entityId),
    index("artifact_kind").on(t.entityId, t.kind),
    index("artifact_status").on(t.entityId, t.status),
    index("artifact_created").on(t.entityId, t.createdAt),
    index("artifact_expires").on(t.expiresAt),
    index("artifact_source_doc").on(t.sourceDocumentId),
  ],
);

// ─── Relations ───────────────────────────────────────────────────────────────

export const artifactRegistryRelations = relations(
  artifactRegistry,
  ({ one }) => ({
    entity: one(entities, {
      fields: [artifactRegistry.entityId],
      references: [entities.id],
    }),
    creator: one(users, {
      fields: [artifactRegistry.createdBy],
      references: [users.id],
    }),
  }),
);
