// ─── Donor & Grant Schema ────────────────────────────────────────────────────
//
// Tracks donor-funded projects and their reporting requirements.
// Enables the Donor/Funder role (read-only, project-scoped) from the RBAC matrix.
//
// Tables:
//   donor_projects         — Donor-funded projects with grant tracking
//   donor_report_snapshots — Generated reports for each project period
//
// Relations:
//   donor_projects.donor_customer_id → customers.id (with is_donor = true)
//   donor_report_snapshots.donor_project_id → donor_projects.id

import {
  pgTable,
  uuid,
  text,
  numeric,
  boolean,
  timestamp,
  jsonb,
  pgEnum,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { uuidId, entityId, timestamps } from "./helpers";
import { customers } from "./ap-ar";
import { entities } from "./organization";

// ─── ENUMS ───────────────────────────────────────

export const donorReportingFormatEnum = pgEnum("donor_reporting_format", [
  "usaid",
  "eu",
  "world_bank",
  "afdb",
  "custom",
]);

export const donorProjectStatusEnum = pgEnum("donor_project_status", [
  "active",
  "completed",
  "suspended",
  "closed",
]);

// ─── DONOR PROJECTS ──────────────────────────────
//
// Each project links a donor (customer with is_donor = true) to a funded
// initiative within an entity. Tracks grant amount, reporting format, and
// project lifecycle.

export const donorProjects = pgTable(
  "donor_projects",
  {
    id: uuidId(),
    entityId: entityId
      .notNull()
      .references(() => entities.id, { onDelete: "cascade" }),
    // The donor customer — must have is_donor = true (enforced at app layer)
    donorCustomerId: uuid("donor_customer_id")
      .notNull()
      .references(() => customers.id),
    projectName: text("project_name").notNull(),
    projectCode: text("project_code"), // Optional short code for internal reference
    grantAmount: numeric("grant_amount", { precision: 15, scale: 2 })
      .notNull()
      .default("0"),
    currency: text("currency").notNull().default("GMD"),
    amountDisbursed: numeric("amount_disbursed", { precision: 15, scale: 2 })
      .notNull()
      .default("0"),
    amountRemaining: numeric("amount_remaining", { precision: 15, scale: 2 })
      .notNull()
      .default("0"),
    reportingFormat: donorReportingFormatEnum("reporting_format")
      .notNull()
      .default("custom"),
    reportingCadence: text("reporting_cadence").default("quarterly"),
    // quarterly | monthly | semi_annual | annual | custom
    startDate: text("start_date").notNull(),
    endDate: text("end_date"),
    status: donorProjectStatusEnum("status").notNull().default("active"),
    description: text("description"),
    budgetAllocation: jsonb("budget_allocation")
      .default({})
      .$type<Record<string, number>>(), // { "category_name": amount, ... }
    isActive: boolean("is_active").notNull().default(true),
    ...timestamps,
  },
  (t) => [
    index("dp_entity").on(t.entityId),
    index("dp_donor").on(t.donorCustomerId),
    index("dp_status").on(t.entityId, t.status),
    index("dp_project_code").on(t.entityId, t.projectCode),
  ],
);

export const donorProjectsRelations = relations(
  donorProjects,
  ({ one, many }) => ({
    entity: one(entities, {
      fields: [donorProjects.entityId],
      references: [entities.id],
    }),
    donor: one(customers, {
      fields: [donorProjects.donorCustomerId],
      references: [customers.id],
    }),
    reportSnapshots: many(donorReportSnapshots),
  }),
);

// ─── DONOR REPORT SNAPSHOTS ──────────────────────
//
// Period snapshots comparing budget vs actual for a donor project.
// Generated by the Reporting Agent or Analytics Agent at the project's
// reporting cadence. Always includes the budget_vs_actual comparison.

export const donorReportSnapshots = pgTable(
  "donor_report_snapshots",
  {
    id: uuidId(),
    entityId: entityId
      .notNull()
      .references(() => entities.id, { onDelete: "cascade" }),
    donorProjectId: uuid("donor_project_id")
      .notNull()
      .references(() => donorProjects.id, { onDelete: "cascade" }),
    period: text("period").notNull(), // e.g. "2026-Q2" or "2026-07"
    budgetVsActual: jsonb("budget_vs_actual").notNull().$type<{
      categories: Array<{
        category: string;
        budgeted: number;
        actual: number;
        variance: number;
        variancePct: number;
      }>;
      totalBudgeted: number;
      totalActual: number;
      totalVariance: number;
      totalVariancePct: number;
    }>(),
    narrativeSummary: text("narrative_summary"), // Generated by Reporting Agent
    status: text("status").notNull().default("draft"),
    // draft | final | submitted | acknowledged
    generatedBy: text("generated_by"), // Agent or user who generated this
    generatedAt: timestamp("generated_at").notNull().defaultNow(),
    submittedAt: timestamp("submitted_at"),
    acknowledgedAt: timestamp("acknowledged_at"),
    documentRef: text("document_ref"), // Link to generated document if exported
    ...timestamps,
  },
  (t) => [
    index("drs_project").on(t.donorProjectId),
    index("drs_entity").on(t.entityId),
    index("drs_period").on(t.donorProjectId, t.period),
    index("drs_status").on(t.entityId, t.status),
  ],
);

export const donorReportSnapshotsRelations = relations(
  donorReportSnapshots,
  ({ one }) => ({
    entity: one(entities, {
      fields: [donorReportSnapshots.entityId],
      references: [entities.id],
    }),
    project: one(donorProjects, {
      fields: [donorReportSnapshots.donorProjectId],
      references: [donorProjects.id],
    }),
  }),
);
