"use client";

import { useState } from "react";
import {
  Search,
  Filter,
  ChevronDown,
  CheckCircle2,
  AlertTriangle,
  Bot,
  TrendingUp,
  FileText,
  MoreHorizontal,
  RefreshCw,
  Send,
  Plus,
  Upload,
  Clock,
  Sparkles,
} from "lucide-react";

import { trpc } from "@/lib/trpc/client";
import { cn } from "@/lib/utils";

// ─── Summary Cards ─────────────────────────────────────────────────────────

function SummaryCards({
  overview,
}: {
  overview: {
    totalEntries: number;
    totalEntriesChange: number;
    totalDebit: number;
    totalCredit: number;
    pendingApproval: number;
    autoGenerated: number;
    autoGeneratedPercent: number;
  };
}) {
  const cards = [
    {
      label: "Total Entries (MTD)",
      value: overview.totalEntries.toString(),
      change: overview.totalEntriesChange,
      icon: FileText,
      color: "text-indigo-600",
      bgColor: "bg-indigo-50",
    },
    {
      label: "Total Debit (MTD)",
      value: `GMD ${overview.totalDebit.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      change: 12.3,
      icon: TrendingUp,
      color: "text-emerald-600",
      bgColor: "bg-emerald-50",
    },
    {
      label: "Total Credit (MTD)",
      value: `GMD ${overview.totalCredit.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      change: 12.3,
      icon: TrendingUp,
      color: "text-blue-600",
      bgColor: "bg-blue-50",
    },
    {
      label: "Pending Approval",
      value: `GMD ${overview.pendingApproval > 0 ? "45,200.00" : "0.00"}`,
      subtitle: `${overview.pendingApproval} entries`,
      icon: Clock,
      color: "text-amber-600",
      bgColor: "bg-amber-50",
    },
    {
      label: "Auto-Generated (MTD)",
      value: `${overview.autoGeneratedPercent}%`,
      subtitle: `${overview.autoGenerated} of ${overview.totalEntries} entries`,
      icon: Sparkles,
      color: "text-purple-600",
      bgColor: "bg-purple-50",
    },
  ];

  return (
    <div className="grid grid-cols-5 gap-4">
      {cards.map((card) => (
        <div
          key={card.label}
          className="rounded-xl border border-slate-200 bg-white p-4"
        >
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm text-slate-500">{card.label}</p>
            <div className={cn("rounded-lg p-2", card.bgColor)}>
              <card.icon className={cn("h-4 w-4", card.color)} />
            </div>
          </div>
          <p className="text-xl font-bold text-slate-900">{card.value}</p>
          {card.change !== undefined && (
            <div className="flex items-center gap-2 mt-1">
              <span
                className={cn(
                  "text-sm font-medium",
                  card.change >= 0 ? "text-emerald-600" : "text-red-600",
                )}
              >
                {card.change >= 0 ? "↑" : "↓"} {Math.abs(card.change)}%
              </span>
              <p className="text-xs text-slate-400">vs last month</p>
            </div>
          )}
          {card.subtitle && card.change === undefined && (
            <p className="text-xs text-slate-400 mt-1">{card.subtitle}</p>
          )}
        </div>
      ))}
    </div>
  );
}

// ─── Journal Table ─────────────────────────────────────────────────────────

function JournalTable({
  entries,
  isLoading,
}: {
  entries: Array<{
    id: string;
    entryNumber: string;
    date: string;
    description: string;
    reference: string | null;
    debit: number;
    debitFormatted: string;
    credit: number;
    creditFormatted: string;
    status: string;
    statusColor: string;
    source: string;
    sourceColor: string;
    createdBy: string;
    isAiGenerated: boolean;
  }>;
  isLoading: boolean;
}) {
  const statusColors: Record<string, string> = {
    Draft: "bg-slate-100 text-slate-600",
    "Pending Approval": "bg-amber-100 text-amber-700",
    Approved: "bg-emerald-100 text-emerald-700",
    Posted: "bg-blue-100 text-blue-700",
    Voided: "bg-red-100 text-red-700",
  };

  const sourceColors: Record<string, string> = {
    Manual: "bg-slate-100 text-slate-700",
    "Bank Import": "bg-blue-100 text-blue-700",
    Automation: "bg-purple-100 text-purple-700",
    Payroll: "bg-amber-100 text-amber-700",
    Inventory: "bg-emerald-100 text-emerald-700",
    "AI Agent": "bg-indigo-100 text-indigo-700",
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-64">
        <RefreshCw className="h-8 w-8 text-slate-400 animate-spin" />
      </div>
    );
  }

  return (
    <div className="overflow-x-auto">
      <table className="w-full">
        <thead>
          <tr className="border-b border-slate-200 bg-slate-50">
            <th className="text-left py-3 px-4">
              <input type="checkbox" className="rounded border-slate-300" />
            </th>
            <th className="text-left py-3 px-4 text-sm font-medium text-slate-600">
              Entry #
            </th>
            <th className="text-left py-3 px-4 text-sm font-medium text-slate-600">
              Date
            </th>
            <th className="text-left py-3 px-4 text-sm font-medium text-slate-600">
              Description
            </th>
            <th className="text-left py-3 px-4 text-sm font-medium text-slate-600">
              Source
            </th>
            <th className="text-left py-3 px-4 text-sm font-medium text-slate-600">
              Reference
            </th>
            <th className="text-right py-3 px-4 text-sm font-medium text-slate-600">
              Debit (GMD)
            </th>
            <th className="text-right py-3 px-4 text-sm font-medium text-slate-600">
              Credit (GMD)
            </th>
            <th className="text-left py-3 px-4 text-sm font-medium text-slate-600">
              Status
            </th>
            <th className="text-left py-3 px-4 text-sm font-medium text-slate-600">
              Created By
            </th>
            <th className="text-left py-3 px-4 text-sm font-medium text-slate-600">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          {entries.map((entry) => (
            <tr
              key={entry.id}
              className="border-b border-slate-100 hover:bg-slate-50 cursor-pointer transition-colors"
            >
              <td className="py-3 px-4">
                <input type="checkbox" className="rounded border-slate-300" />
              </td>
              <td className="py-3 px-4">
                <span className="text-sm font-medium text-indigo-600">
                  {entry.entryNumber}
                </span>
              </td>
              <td className="py-3 px-4 text-sm text-slate-600">
                {new Date(entry.date).toLocaleDateString("en-US", {
                  month: "short",
                  day: "numeric",
                  year: "numeric",
                })}
              </td>
              <td className="py-3 px-4">
                <p className="text-sm font-medium text-slate-900">
                  {entry.description}
                </p>
              </td>
              <td className="py-3 px-4">
                <span
                  className={cn(
                    "inline-flex items-center rounded-full px-2 py-1 text-xs font-medium",
                    sourceColors[entry.source] || sourceColors.Manual,
                  )}
                >
                  {entry.source}
                </span>
              </td>
              <td className="py-3 px-4 text-sm text-slate-600">
                {entry.reference ?? "—"}
              </td>
              <td className="py-3 px-4 text-right">
                <span className="text-sm font-medium text-slate-900">
                  {entry.debit > 0 ? entry.debitFormatted : "—"}
                </span>
              </td>
              <td className="py-3 px-4 text-right">
                <span className="text-sm font-medium text-slate-900">
                  {entry.credit > 0 ? entry.creditFormatted : "—"}
                </span>
              </td>
              <td className="py-3 px-4">
                <span
                  className={cn(
                    "inline-flex items-center rounded-full px-2 py-1 text-xs font-medium",
                    statusColors[entry.status] || statusColors.Draft,
                  )}
                >
                  {entry.status}
                </span>
              </td>
              <td className="py-3 px-4">
                <div className="flex items-center gap-2">
                  <span className="text-sm text-slate-600">
                    {entry.createdBy}
                  </span>
                  {entry.isAiGenerated && (
                    <Sparkles className="h-3 w-3 text-purple-500" />
                  )}
                </div>
              </td>
              <td className="py-3 px-4">
                <button className="p-1 hover:bg-slate-100 rounded">
                  <MoreHorizontal className="h-4 w-4 text-slate-400" />
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ─── AI Copilot Panel ──────────────────────────────────────────────────────

function AiCopilotPanel({
  insights,
  sources,
  recentActivity,
}: {
  insights: Array<{
    id: string;
    type: "warning" | "info" | "success";
    title: string;
    description: string;
    actionLabel: string;
  }>;
  sources: {
    sources: Array<{
      name: string;
      count: number;
      percent: number;
      color: string;
    }>;
    totalCount: number;
  };
  recentActivity: Array<{
    id: string;
    entryNumber: string;
    action: string;
    timestamp: string;
    user: string;
  }>;
}) {
  const [message, setMessage] = useState("");

  const quickActions = [
    "Why is this entry out of balance?",
    "Show me entries by source",
    "Which entries are pending approval?",
    "Summarize journal entries this month",
  ];

  const sourceColors = [
    "bg-slate-500",
    "bg-blue-500",
    "bg-purple-500",
    "bg-amber-500",
    "bg-emerald-500",
  ];

  return (
    <div className="h-full flex flex-col bg-white border-l border-slate-200">
      {/* Header */}
      <div className="border-b border-slate-200 p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <div className="h-8 w-8 rounded-full bg-gradient-to-br from-indigo-500 to-purple-500 flex items-center justify-center">
              <Bot className="h-4 w-4 text-white" />
            </div>
            <div>
              <h3 className="font-medium text-slate-900">Xenboox AI Copilot</h3>
              <span className="inline-flex items-center rounded-full bg-indigo-100 px-2 py-0.5 text-xs font-medium text-indigo-700">
                Beta
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-4 space-y-6">
        {/* Greeting */}
        <div>
          <p className="text-sm text-slate-600">
            I analyzed your journal entries and found a few insights.
          </p>
        </div>

        {/* AI Insights */}
        <div className="space-y-3">
          {insights.map((insight) => (
            <div
              key={insight.id}
              className={cn(
                "rounded-xl border p-4",
                insight.type === "warning"
                  ? "border-amber-200 bg-amber-50"
                  : insight.type === "success"
                    ? "border-emerald-200 bg-emerald-50"
                    : "border-blue-200 bg-blue-50",
              )}
            >
              <div className="flex items-start gap-3">
                <div
                  className={cn(
                    "h-6 w-6 rounded-full flex items-center justify-center mt-0.5",
                    insight.type === "warning"
                      ? "bg-amber-100"
                      : insight.type === "success"
                        ? "bg-emerald-100"
                        : "bg-blue-100",
                  )}
                >
                  {insight.type === "warning" ? (
                    <AlertTriangle className="h-3 w-3 text-amber-600" />
                  ) : insight.type === "success" ? (
                    <CheckCircle2 className="h-3 w-3 text-emerald-600" />
                  ) : (
                    <Clock className="h-3 w-3 text-blue-600" />
                  )}
                </div>
                <div className="flex-1">
                  <p className="text-sm font-medium text-slate-900">
                    {insight.title}
                  </p>
                  <p className="text-xs text-slate-600 mt-1">
                    {insight.description}
                  </p>
                  <button className="text-xs font-medium text-indigo-600 hover:text-indigo-700 mt-2">
                    {insight.actionLabel} →
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Ask me anything */}
        <div>
          <div className="space-y-2">
            {quickActions.map((action, i) => (
              <button
                key={i}
                className="w-full text-left flex items-center gap-3 px-3 py-2.5 text-sm text-slate-700 hover:bg-indigo-50 hover:text-indigo-700 rounded-lg border border-slate-200 transition-colors"
              >
                <Bot className="h-4 w-4 text-slate-400" />
                {action}
              </button>
            ))}
          </div>
        </div>

        {/* Journal Entry Sources (MTD) */}
        <div>
          <div className="flex items-center justify-between mb-3">
            <h4 className="text-sm font-medium text-slate-900">
              Journal Entry Sources (MTD)
            </h4>
          </div>

          <div className="flex items-center gap-4">
            {/* Donut Chart */}
            <div className="relative">
              <svg className="h-32 w-32" viewBox="0 0 100 100">
                {sources.sources.map((source, i) => {
                  const startAngle = sources.sources
                    .slice(0, i)
                    .reduce((acc, s) => acc + (s.percent / 100) * 360, 0);
                  const endAngle = startAngle + (source.percent / 100) * 360;
                  const largeArc = source.percent > 50 ? 1 : 0;
                  const x1 =
                    50 + 40 * Math.cos((startAngle - 90) * (Math.PI / 180));
                  const y1 =
                    50 + 40 * Math.sin((startAngle - 90) * (Math.PI / 180));
                  const x2 =
                    50 + 40 * Math.cos((endAngle - 90) * (Math.PI / 180));
                  const y2 =
                    50 + 40 * Math.sin((endAngle - 90) * (Math.PI / 180));
                  const x3 =
                    50 + 25 * Math.cos((endAngle - 90) * (Math.PI / 180));
                  const y3 =
                    50 + 25 * Math.sin((endAngle - 90) * (Math.PI / 180));
                  const x4 =
                    50 + 25 * Math.cos((startAngle - 90) * (Math.PI / 180));
                  const y4 =
                    50 + 25 * Math.sin((startAngle - 90) * (Math.PI / 180));

                  return (
                    <path
                      key={source.name}
                      d={`M ${x1} ${y1} A 40 40 0 ${largeArc} 1 ${x2} ${y2} L ${x3} ${y3} A 25 25 0 ${largeArc} 0 ${x4} ${y4} Z`}
                      className={sourceColors[i % sourceColors.length]}
                      fill="currentColor"
                    />
                  );
                })}
              </svg>
              <div className="absolute inset-0 flex items-center justify-center">
                <div className="text-center">
                  <p className="text-lg font-bold text-slate-900">
                    {sources.totalCount}
                  </p>
                  <p className="text-[10px] text-slate-500">Total</p>
                </div>
              </div>
            </div>

            {/* Legend */}
            <div className="flex-1 space-y-2">
              {sources.sources.map((source, i) => (
                <div
                  key={source.name}
                  className="flex items-center justify-between"
                >
                  <div className="flex items-center gap-2">
                    <div
                      className={cn(
                        "h-3 w-3 rounded-full",
                        sourceColors[i % sourceColors.length],
                      )}
                    />
                    <span className="text-xs text-slate-600">
                      {source.name}
                    </span>
                  </div>
                  <span className="text-xs text-slate-500">
                    {source.count} ({source.percent}%)
                  </span>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Quick Actions */}
        <div>
          <h4 className="text-sm font-medium text-slate-900 mb-3">
            Quick Actions
          </h4>
          <div className="grid grid-cols-2 gap-2">
            <button className="flex items-center gap-2 px-3 py-2 text-sm text-slate-700 hover:bg-slate-50 rounded-lg border border-slate-200">
              <Plus className="h-4 w-4 text-indigo-600" />
              New Journal Entry
            </button>
            <button className="flex items-center gap-2 px-3 py-2 text-sm text-slate-700 hover:bg-slate-50 rounded-lg border border-slate-200">
              <Upload className="h-4 w-4 text-emerald-600" />
              Import Entries
            </button>
            <button className="flex items-center gap-2 px-3 py-2 text-sm text-slate-700 hover:bg-slate-50 rounded-lg border border-slate-200">
              <RefreshCw className="h-4 w-4 text-blue-600" />
              Recurring Entries
            </button>
            <button className="flex items-center gap-2 px-3 py-2 text-sm text-slate-700 hover:bg-slate-50 rounded-lg border border-slate-200">
              <FileText className="h-4 w-4 text-purple-600" />
              Journal Entry Report
            </button>
          </div>
        </div>
      </div>

      {/* Input */}
      <div className="border-t border-slate-200 p-4">
        <div className="flex items-center gap-2">
          <input
            type="text"
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            placeholder="Ask anything about journal entries..."
            className="flex-1 rounded-lg border border-slate-200 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
          />
          <button className="h-9 w-9 rounded-lg bg-indigo-600 flex items-center justify-center text-white hover:bg-indigo-700">
            <Send className="h-4 w-4" />
          </button>
        </div>
      </div>
    </div>
  );
}

// ─── Bottom Row ────────────────────────────────────────────────────────────

function BottomRow({
  topAccounts,
  recentActivity,
}: {
  topAccounts: Array<{
    name: string;
    debit: number;
    debitFormatted: string;
    credit: number;
    creditFormatted: string;
  }>;
  recentActivity: Array<{
    id: string;
    entryNumber: string;
    action: string;
    timestamp: string;
    user: string;
  }>;
}) {
  // Mock trend data (would come from API in production)
  const trendData = [
    { month: "Dec", count: 85 },
    { month: "Jan", count: 92 },
    { month: "Feb", count: 78 },
    { month: "Mar", count: 105 },
    { month: "Apr", count: 98 },
    { month: "May", count: 132 },
  ];

  const maxTrend = Math.max(...trendData.map((d) => d.count));

  const activityIcons: Record<
    string,
    { icon: typeof CheckCircle2; color: string }
  > = {
    posted: { icon: CheckCircle2, color: "text-emerald-500" },
    "submitted for approval": { icon: Clock, color: "text-amber-500" },
    created: { icon: Plus, color: "text-blue-500" },
    voided: { icon: AlertTriangle, color: "text-red-500" },
  };

  return (
    <div className="grid grid-cols-3 gap-6">
      {/* Journal Entry Trend */}
      <div className="rounded-xl border border-slate-200 bg-white p-5">
        <div className="flex items-center justify-between mb-4">
          <h4 className="text-sm font-medium text-slate-900">
            Journal Entry Trend
          </h4>
          <select className="text-xs text-slate-500 border border-slate-200 rounded px-2 py-1">
            <option>Last 6 months</option>
          </select>
        </div>

        {/* Line Chart */}
        <div className="h-32 flex items-end gap-2">
          {trendData.map((d, _i) => {
            const height = maxTrend > 0 ? (d.count / maxTrend) * 100 : 0;
            return (
              <div
                key={d.month}
                className="flex-1 flex flex-col items-center gap-1"
              >
                <div className="w-full relative" style={{ height: "80px" }}>
                  <div
                    className="absolute bottom-0 w-full bg-gradient-to-t from-indigo-500 to-indigo-400 rounded-t"
                    style={{ height: `${height}%` }}
                  />
                </div>
                <span className="text-[10px] text-slate-500">{d.month}</span>
              </div>
            );
          })}
        </div>
      </div>

      {/* Top Account Impact */}
      <div className="rounded-xl border border-slate-200 bg-white p-5">
        <div className="flex items-center justify-between mb-4">
          <h4 className="text-sm font-medium text-slate-900">
            Top Account Impact (MTD)
          </h4>
          <button className="text-xs font-medium text-indigo-600 hover:text-indigo-700">
            View full report →
          </button>
        </div>
        <div className="space-y-3">
          {topAccounts.map((account) => (
            <div
              key={account.name}
              className="flex items-center justify-between py-2 border-b border-slate-100 last:border-0"
            >
              <span className="text-sm text-slate-700">{account.name}</span>
              <div className="flex items-center gap-4">
                <span className="text-sm font-medium text-slate-900 w-24 text-right">
                  {account.debitFormatted}
                </span>
                <span className="text-sm font-medium text-slate-900 w-24 text-right">
                  {account.creditFormatted}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Recent Activity */}
      <div className="rounded-xl border border-slate-200 bg-white p-5">
        <div className="flex items-center justify-between mb-4">
          <h4 className="text-sm font-medium text-slate-900">
            Recent Activity
          </h4>
          <button className="text-xs font-medium text-indigo-600 hover:text-indigo-700">
            View all activity →
          </button>
        </div>
        <div className="space-y-4">
          {recentActivity.map((activity) => {
            const activityConfig =
              activityIcons[activity.action] ?? activityIcons.created;
            const Icon = activityConfig.icon;
            return (
              <div key={activity.id} className="flex items-start gap-3">
                <Icon className={cn("h-5 w-5 mt-0.5", activityConfig.color)} />
                <div>
                  <p className="text-sm text-slate-900">
                    <span className="font-medium">{activity.entryNumber}</span>{" "}
                    was {activity.action}
                  </p>
                  <p className="text-xs text-slate-500">
                    by {activity.user} •{" "}
                    {new Date(activity.timestamp).toLocaleString("en-US", {
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}

// ─── Main Page ─────────────────────────────────────────────────────────────

export default function JournalEntriesPage() {
  const [activeTab, setActiveTab] = useState<
    "all" | "draft" | "pending" | "approved" | "posted" | "voided"
  >("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [page, setPage] = useState(1);
  const [pageSize] = useState(10);

  // Fetch overview
  const { data: overview } = trpc.journal.getOverview.useQuery({});

  // Fetch tab counts
  const { data: tabCounts } = trpc.journal.getTabCounts.useQuery();

  // Fetch entries
  const { data: entriesData, isLoading: entriesLoading } =
    trpc.journal.listWithDetails.useQuery({
      status: activeTab,
      search: searchQuery || undefined,
      limit: pageSize,
      offset: (page - 1) * pageSize,
    });

  // Fetch top accounts
  const { data: topAccounts } = trpc.journal.getTopAccountImpact.useQuery({
    limit: 5,
  });

  // Fetch sources
  const { data: sources } = trpc.journal.getEntrySources.useQuery({});

  // Fetch recent activity
  const { data: recentActivity } = trpc.journal.getRecentActivity.useQuery();

  // Fetch AI insights
  const { data: insights } = trpc.journal.getAiInsights.useQuery();

  const tabs = [
    { key: "all" as const, label: "All Entries", count: tabCounts?.all },
    { key: "draft" as const, label: "Draft", count: tabCounts?.draft },
    {
      key: "pending" as const,
      label: "Pending Approval",
      count: tabCounts?.pending,
    },
    { key: "approved" as const, label: "Approved", count: tabCounts?.approved },
    { key: "posted" as const, label: "Posted", count: tabCounts?.posted },
    { key: "voided" as const, label: "Voided", count: tabCounts?.voided },
  ];

  return (
    <div className="h-[calc(100vh-4rem)] flex">
      {/* Main Content */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Header */}
        <div className="border-b border-slate-200 bg-white p-4">
          <div className="flex items-center justify-between mb-4">
            <div>
              <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-3">
                <span className="text-2xl">📒</span>
                Journal Entries
              </h1>
              <p className="text-sm text-slate-500 mt-1">
                Create, review, and manage journal entries with AI assistance.
              </p>
            </div>
            <div className="flex items-center gap-3">
              <button className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700">
                <Plus className="h-4 w-4" />
                New Journal Entry
              </button>
              <button className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">
                <Upload className="h-4 w-4" />
                Import
              </button>
              <button className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">
                More
                <ChevronDown className="h-4 w-4" />
              </button>
            </div>
          </div>

          {/* Tabs */}
          <div className="flex items-center gap-1">
            {tabs.map((tab) => (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key)}
                className={cn(
                  "px-4 py-2 text-sm font-medium rounded-lg transition-colors",
                  activeTab === tab.key
                    ? "bg-indigo-50 text-indigo-600"
                    : "text-slate-500 hover:text-slate-700 hover:bg-slate-50",
                )}
              >
                {tab.label}
                {tab.count !== undefined && (
                  <span
                    className={cn(
                      "ml-2 px-2 py-0.5 rounded-full text-xs",
                      activeTab === tab.key
                        ? "bg-indigo-100 text-indigo-700"
                        : "bg-slate-100 text-slate-600",
                    )}
                  >
                    {tab.count}
                  </span>
                )}
              </button>
            ))}
          </div>
        </div>

        {/* Summary Cards */}
        {overview && (
          <div className="p-4 bg-slate-50 border-b border-slate-200">
            <SummaryCards overview={overview} />
          </div>
        )}

        {/* Filters */}
        <div className="p-4 bg-white border-b border-slate-200">
          <div className="flex items-center gap-3">
            <div className="flex-1 relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-400" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search journal entries..."
                className="w-full rounded-lg border border-slate-200 pl-10 pr-4 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent"
              />
            </div>
            <select className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500">
              <option>All Dates</option>
              <option>Today</option>
              <option>This week</option>
              <option>This month</option>
              <option>Custom range</option>
            </select>
            <select className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500">
              <option>All Sources</option>
              <option>Manual</option>
              <option>Bank Import</option>
              <option>Automation</option>
              <option>Payroll</option>
              <option>Inventory</option>
            </select>
            <select className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500">
              <option>All Statuses</option>
              <option>Draft</option>
              <option>Pending Approval</option>
              <option>Posted</option>
              <option>Voided</option>
            </select>
            <select className="rounded-lg border border-slate-200 px-3 py-2 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500">
              <option>All Users</option>
            </select>
            <button className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">
              <Filter className="h-4 w-4" />
              Filters
            </button>
          </div>
        </div>

        {/* Journal Table */}
        <div className="flex-1 overflow-auto bg-white">
          <JournalTable
            entries={entriesData?.entries ?? []}
            isLoading={entriesLoading}
          />
        </div>

        {/* Pagination */}
        <div className="border-t border-slate-200 bg-white p-4">
          <div className="flex items-center justify-between">
            <p className="text-sm text-slate-500">
              Showing {(page - 1) * pageSize + 1} to{" "}
              {Math.min(page * pageSize, entriesData?.totalCount ?? 0)} of{" "}
              {entriesData?.totalCount ?? 0} entries
            </p>
            <div className="flex items-center gap-2">
              <button
                onClick={() => setPage(Math.max(1, page - 1))}
                disabled={page === 1}
                className="px-3 py-1.5 text-sm text-slate-600 hover:bg-slate-50 rounded disabled:opacity-50"
              >
                ←
              </button>
              {Array.from(
                { length: Math.min(5, entriesData?.totalPages ?? 1) },
                (_, i) => i + 1,
              ).map((p) => (
                <button
                  key={p}
                  onClick={() => setPage(p)}
                  className={cn(
                    "px-3 py-1.5 text-sm rounded",
                    page === p
                      ? "bg-indigo-600 text-white"
                      : "text-slate-600 hover:bg-slate-50",
                  )}
                >
                  {p}
                </button>
              ))}
              <button
                onClick={() =>
                  setPage(Math.min(entriesData?.totalPages ?? 1, page + 1))
                }
                disabled={page === (entriesData?.totalPages ?? 1)}
                className="px-3 py-1.5 text-sm text-slate-600 hover:bg-slate-50 rounded disabled:opacity-50"
              >
                →
              </button>
              <select
                value={pageSize}
                onChange={() => setPage(1)}
                className="ml-4 rounded-lg border border-slate-200 px-3 py-1.5 text-sm text-slate-700 focus:outline-none focus:ring-2 focus:ring-indigo-500"
              >
                <option value={10}>10 / page</option>
                <option value={25}>25 / page</option>
                <option value={50}>50 / page</option>
              </select>
            </div>
          </div>
        </div>

        {/* Bottom Row */}
        <div className="p-4 bg-slate-50 border-t border-slate-200">
          <BottomRow
            topAccounts={topAccounts ?? []}
            recentActivity={recentActivity ?? []}
          />
        </div>
      </div>

      {/*
        AI Copilot Panel - DISABLED
        <div className="w-[360px]">
          <AiCopilotPanel
            insights={insights ?? []}
            sources={sources ?? { sources: [], totalCount: 0 }}
            recentActivity={recentActivity ?? []}
          />
        </div>
      */}
    </div>
  );
}
