"use client";

import { useState, useCallback, useRef } from "react";

import type { PageContextPayload } from "@/lib/chat/page-context";
import type { PinnedContext } from "@/lib/chat/mention-types";

// ─── Event Types ───────────────────────────────────────────────────────────

export interface AgentActivityEvent {
  type: "agent_activity";
  agent: string;
  status: "started" | "completed" | "failed";
  action: string;
  confidence?: number;
  durationMs?: number;
}

/**
 * Live "thinking" event — a real pipeline step revealed to the user, same
 * visual language as the simulation traces (shimmer → reasoning → settled).
 */
export interface ThinkingEvent {
  type: "thinking";
  agent: string;
  /** Stable pipeline step id (e.g. "intent_resolution"). */
  step?: string;
  label?: string;
  text: string;
  durationMs?: number;
}

export interface DelegationEvent {
  type: "delegation";
  from: string;
  to: string;
  reason: string;
}

export interface DocumentCreatedEvent {
  type: "document_created";
  /** Artifact registry ID of the generated file. */
  artifactId: string;
  name: string;
  /** Display label, e.g. "Report", "Export". */
  docType: string;
  mimeType: string;
  sizeBytes?: number;
  url?: string;
}

export interface ApprovalEvent {
  type: "approval_needed";
  title: string;
  description: string;
  amount?: string;
}

export interface NeedsInputField {
  field: string;
  label: string;
  type: "text" | "number" | "date" | "select" | "textarea";
  required: boolean;
  options?: string[];
}

export interface NeedsInputEvent {
  type: "needs_input";
  action: string;
  missing: NeedsInputField[];
  context?: Record<string, unknown>;
}

export interface ToolCallEvent {
  type: "tool_call";
  toolName: string;
  args?: Record<string, unknown>;
  timestamp?: string;
}

export interface ToolResultEvent {
  type: "tool_result";
  toolName: string;
  success: boolean;
  data?: unknown;
  timestamp?: string;
}

export interface ToolTrace {
  toolName: string;
  args?: Record<string, unknown>;
  status: "running" | "success" | "failed";
  durationMs?: number;
}

export interface KnowledgeCitationEvent {
  type: "knowledge_citations";
  citations: Array<{
    index: number;
    content: string;
    sourceType: string;
    documentId?: string;
    score: number;
    method: string;
  }>;
  totalChunks?: number;
  method?: string;
  durationMs?: number;
}

export interface DataTableColumn {
  key: string;
  label: string;
  sortable?: boolean;
  align?: "left" | "center" | "right";
  format?: "currency" | "number" | "percent" | "date" | "text";
  currency?: string;
}

export interface DataTableRow {
  id: string;
  cells: Record<string, string | number | boolean | null>;
  detail?: Record<string, string | number | boolean | null>;
}

export interface DataTableSummary {
  label: string;
  cells: Record<string, string | number | boolean | null>;
}

export interface ChartSeries {
  key: string;
  label: string;
  color?: string;
  type?: "bar" | "line" | "area";
}

export interface ChartEvent {
  type: "chart";
  chartType: "bar" | "line" | "area" | "pie" | "donut" | "sparkline";
  title?: string;
  data: Array<Record<string, string | number>>;
  xKey?: string;
  yKey?: string;
  series?: ChartSeries[];
  currency?: string;
  summary?: string;
}

export interface DataTableEvent {
  type: "data_table";
  title?: string;
  columns: DataTableColumn[];
  rows: DataTableRow[];
  summary?: DataTableSummary;
  currency?: string;
}

export interface BatchIngestionResultEvent {
  type: "batch_ingestion_result";
  batchId: string;
  totalDocuments: number;
  completedDocuments: number;
  failedDocuments: number;
  documents: Array<{
    documentId: string;
    fileName: string;
    status: string;
    chunksCreated?: number;
  }>;
  message?: string;
}

export interface TokenEvent {
  type: "token";
  content: string;
}

export interface DoneEvent {
  type: "done";
  messageId: string;
  confidence: number;
  agentsInvolved: string[];
  durationMs?: number;
}

export interface ConversationEvent {
  type: "conversation";
  conversationId: string;
  /** Readable name generated by the server for this conversation. */
  title?: string;
}

export interface ErrorEvent {
  type: "error";
  code?: string;
  message: string;
}

type SSEEvent =
  | ConversationEvent
  | AgentActivityEvent
  | ThinkingEvent
  | DelegationEvent
  | DocumentCreatedEvent
  | ApprovalEvent
  | ChartEvent
  | DataTableEvent
  | ToolCallEvent
  | ToolResultEvent
  | TokenEvent
  | DoneEvent
  | ErrorEvent;

// ─── Hook Options ──────────────────────────────────────────────────────────

interface UseStreamingChatOptions {
  entityId: string;
  onConversationCreated?: (conversationId: string, title?: string) => void;
  onAgentActivity?: (activity: AgentActivityEvent) => void;
  onThinking?: (event: ThinkingEvent) => void;
  onDelegation?: (delegation: DelegationEvent) => void;
  onDocumentCreated?: (doc: DocumentCreatedEvent) => void;
  onApprovalNeeded?: (approval: ApprovalEvent) => void;
  onKnowledgeCitations?: (citations: KnowledgeCitationEvent) => void;
  onBatchIngestionResult?: (result: BatchIngestionResultEvent) => void;
  onNeedsInput?: (input: NeedsInputEvent) => void;
  onDataTable?: (table: DataTableEvent) => void;
  onChart?: (chart: ChartEvent) => void;
  onToolCall?: (trace: ToolTrace) => void;
  onToken?: (token: string) => void;
  onComplete?: (fullResponse: string, metadata: DoneEvent) => void;
  onError?: (error: string) => void;
}

// ─── Hook ──────────────────────────────────────────────────────────────────

export function useStreamingChat({
  entityId,
  onConversationCreated,
  onAgentActivity,
  onThinking,
  onDelegation,
  onDocumentCreated,
  onApprovalNeeded,
  onKnowledgeCitations,
  onBatchIngestionResult,
  onNeedsInput,
  onDataTable,
  onChart,
  onToolCall,
  onToken,
  onComplete,
  onError,
}: UseStreamingChatOptions) {
  const [isStreaming, setIsStreaming] = useState(false);
  const [streamedContent, setStreamedContent] = useState("");
  const [agentActivities, setAgentActivities] = useState<AgentActivityEvent[]>(
    [],
  );
  const [thinkingEvents, setThinkingEvents] = useState<ThinkingEvent[]>([]);
  const [delegations, setDelegations] = useState<DelegationEvent[]>([]);
  const [approvals, setApprovals] = useState<ApprovalEvent[]>([]);
  const [documents, setDocuments] = useState<DocumentCreatedEvent[]>([]);
  const [toolTraces, setToolTraces] = useState<ToolTrace[]>([]);
  const [dataTables, setDataTables] = useState<DataTableEvent[]>([]);
  const [charts, setCharts] = useState<ChartEvent[]>([]);
  const abortControllerRef = useRef<AbortController | null>(null);

  const sendMessage = useCallback(
    async (
      message: string,
      conversationId?: string,
      files?: Array<{ documentId: string; name: string; type: string }>,
      pageContext?: PageContextPayload,
      pinned?: PinnedContext[],
    ) => {
      if (isStreaming) return;

      setIsStreaming(true);
      setStreamedContent("");
      setAgentActivities([]);
      setThinkingEvents([]);
      setDelegations([]);
      setApprovals([]);
      setDocuments([]);
      setToolTraces([]);
      setDataTables([]);
      setCharts([]);

      try {
        abortControllerRef.current = new AbortController();

        const response = await fetch("/api/chat/stream", {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            message,
            conversationId,
            entityId,
            files,
            pageContext,
            pinned,
          }),
          signal: abortControllerRef.current.signal,
        });

        if (!response.ok) {
          throw new Error("Failed to send message");
        }

        const reader = response.body?.getReader();
        if (!reader) {
          throw new Error("No response body");
        }

        const decoder = new TextDecoder();
        let fullResponse = "";

        while (true) {
          const { done, value } = await reader.read();
          if (done) break;

          const chunk = decoder.decode(value);
          const lines = chunk.split("\n");

          for (const line of lines) {
            if (line.startsWith("data: ")) {
              try {
                const data: SSEEvent = JSON.parse(line.slice(6));

                switch (data.type) {
                  case "conversation":
                    onConversationCreated?.(data.conversationId, data.title);
                    break;

                  case "agent_activity":
                    setAgentActivities((prev) => [...prev, data]);
                    onAgentActivity?.(data);
                    break;

                  case "thinking":
                    setThinkingEvents((prev) => [...prev, data]);
                    onThinking?.(data);
                    break;

                  case "delegation":
                    setDelegations((prev) => [...prev, data]);
                    onDelegation?.(data);
                    break;

                  case "document_created":
                    setDocuments((prev) => [...prev, data]);
                    onDocumentCreated?.(data);
                    break;

                  case "approval_needed":
                    setApprovals((prev) => [...prev, data]);
                    onApprovalNeeded?.(data);
                    break;

                  case "needs_input":
                    onNeedsInput?.(data as NeedsInputEvent);
                    break;

                  case "data_table":
                    setDataTables((prev) => [...prev, data as DataTableEvent]);
                    onDataTable?.(data as DataTableEvent);
                    break;

                  case "chart":
                    setCharts((prev) => [...prev, data as ChartEvent]);
                    onChart?.(data as ChartEvent);
                    break;

                  case "knowledge_citations":
                    onKnowledgeCitations?.(data as KnowledgeCitationEvent);
                    break;

                  case "batch_ingestion_result":
                    onBatchIngestionResult?.(data as BatchIngestionResultEvent);
                    break;

                  case "tool_call": {
                    const trace: ToolTrace = {
                      toolName: data.toolName,
                      args: data.args,
                      status: "running",
                    };
                    setToolTraces((prev) => [...prev, trace]);
                    onToolCall?.(trace);
                    break;
                  }

                  case "tool_result": {
                    setToolTraces((prev) => {
                      // Complete the most recent running trace with this name.
                      let idx = -1;
                      for (let i = prev.length - 1; i >= 0; i--) {
                        if (
                          prev[i].toolName === data.toolName &&
                          prev[i].status === "running"
                        ) {
                          idx = i;
                          break;
                        }
                      }
                      if (idx === -1) return prev;
                      const next = [...prev];
                      next[idx] = {
                        ...next[idx],
                        status: data.success ? "success" : "failed",
                      };
                      return next;
                    });
                    break;
                  }

                  case "token":
                    if (data.content) {
                      fullResponse += data.content;
                      setStreamedContent(fullResponse);
                      onToken?.(data.content);
                    }
                    break;

                  case "done":
                    onComplete?.(fullResponse, data);
                    break;

                  case "error":
                    onError?.(data.message || "Unknown error");
                    break;
                }
              } catch {
                // Skip invalid JSON lines
              }
            }
          }
        }
      } catch (error) {
        if (error instanceof Error && error.name === "AbortError") {
          // User cancelled
        } else {
          onError?.(
            error instanceof Error ? error.message : "Failed to send message",
          );
        }
      } finally {
        setIsStreaming(false);
        abortControllerRef.current = null;
      }
    },
    [
      entityId,
      isStreaming,
      onConversationCreated,
      onAgentActivity,
      onThinking,
      onDelegation,
      onDocumentCreated,
      onApprovalNeeded,
      onNeedsInput,
      onDataTable,
      onChart,
      onToolCall,
      onToken,
      onComplete,
      onError,
    ],
  );

  const cancelStream = useCallback(() => {
    abortControllerRef.current?.abort();
    setIsStreaming(false);
  }, []);

  return {
    sendMessage,
    cancelStream,
    isStreaming,
    streamedContent,
    agentActivities,
    thinkingEvents,
    delegations,
    approvals,
    documents,
    toolTraces,
    dataTables,
    charts,
  };
}
