// ─── Core Infrastructure ─────────────────────────────────────────────────────
export {
  getLangfuse,
  langfuse,
  getLLMRegistry,
  callLLM,
  streamLLM,
  calculateCost,
  buildCostEntry,
  callModel,
  streamModel,
  getModelRouter,
  ModelRouter,
  getAssignment,
  invalidateAssignment,
  invalidateAllAssignments,
  runGate1,
  runGate2,
  runGate3,
  runGate4,
  rollbackModel,
  recordShadowComparison,
  recordCanaryMetric,
  checkEntityAccess,
  getAgentTier,
  isTaskTypeAllowedForAgent,
  getCredentialVault,
  CredentialVault,
  BaseAgentState,
  AuditEntrySchema,
  AgentMessageSchema,
  createAuditEntry,
  validateDoubleEntry,
  getAccountBalance,
  getJournalEntryLines,
  getRecentJournalEntries,
  getAccountByCode,
  computeCompositeConfidence,
  computePrecedentMatch,
  computeDataCompleteness,
  computeAmountExactness,
  computeDateProximity,
  computeReferenceSimilarity,
  makeEscalationDecision,
  checkMaterialAmountOverride,
  detectConflictingOutputs,
  computeCalibrationScore,
  DEFAULT_ESCALATION_CONFIG,
  CFO_SYSTEM_PROMPT,
  CONTROLLER_SYSTEM_PROMPT,
  LEDGER_SYSTEM_PROMPT,
  orchestrate,
  classifyUserMessage,
  orchestrateHierarchical,
  fanOutToDepartments,
  checkEscalation,
  getAgentGraph,
  AGENT_REGISTRY,
  TASK_TO_AGENT,
  DEPARTMENT_AGENTS,
  DEPARTMENT_CLOSE_TASK,
  ALL_DEPARTMENTS,
  runReconciliationPipeline,
  getReconciliationStatus,
  runCashPipeline,
  runReportingPipeline,
  detectReportablePeriods,
  runOnboardingPipeline,
} from "./core";
export type {
  ModelTier,
  ModelRoute,
  ProviderName,
  LLMCallParams,
  LLMCallResult,
  LLMStreamCallbacks,
  CallModelParams,
  NormalizedModelResponse,
  NormalizedToolCall,
  ProviderId,
  TaskType,
  AssignmentRecord,
  AgentTierLevel,
  EntityAccessCheck,
  CredentialEntry,
  BaseAgentStateType,
  AuditEntry,
  AgentMessage,
  CompositeConfidence,
  ConfidenceSignal,
  EscalationDecision,
  EscalationConfig,
  AgentTaskType,
  AgentTier,
  AgentId,
  AgentTask,
  AgentResult,
  OrchestrateParams,
  DepartmentResult,
  EscalationAction,
  AgentDepartment,
  BankReconciliationResult,
  ReconciliationItemResult,
  ReconciliationPipelineResult,
  CashPipelineResult,
  CashPosition,
  ImprestStatus,
  DiscrepancyItem,
  ReportingPipelineResult,
  ReportData,
  ReportablePeriod,
  OnboardingPipelineResult,
  OnboardingStep,
} from "./core";

// ─── Eval Harness ────────────────────────────────────────────────────────────
export { EvalRunner, EvalSuite } from "./core/eval/harness";
export { runEval } from "./core/eval/runner";
export type {
  EvalCase,
  EvalCaseCategory,
  EvalCaseSource,
  EvalResult,
  SingleAgentEvalSummary,
  EvalSuiteSummary,
  EvalConfig,
  FlowEvalResult,
  FlowStepResult,
} from "./core/eval/types";

// ─── Tier 1: CFO Agent (Strategic) ──────────────────────────────────────────
export { cfoAgent } from "./tier1";
export type {
  CfoStateType,
  DepartmentConfirmation,
  EscalationItem,
  InstructionType,
  Department,
} from "./tier1";

// ─── Tier 2: Management Agents ──────────────────────────────────────────────
export {
  controllerAgent,
  treasuryAgent,
  payrollManagerAgent,
  complianceAgent,
} from "./tier2";
export type {
  ControllerStateType,
  PendingEntryReview,
  SubLedgerStatus,
  CloseChecklist,
  TreasuryStateType,
  PayrollManagerStateType,
  ComplianceStateType,
} from "./tier2";

// ─── Tier 3: Worker Agents ──────────────────────────────────────────────────
export {
  ledgerAgent,
  apAgent,
  arAgent,
  assetAgent,
  inventoryAgent,
  reconciliationAgent,
  cashAgent,
  mobileMoneyAgent,
  payrollWorkerAgent,
} from "./tier3";
export type {
  LedgerStateType,
  PendingEntry,
  TrialBalance,
  ApStateType,
  CurrentInvoice,
  AgingReport,
  PaymentScheduleItem,
  ArStateType,
  AssetStateType,
  AssetItem,
  DepreciationResult,
  InventoryStateType,
  InventorySummary,
  InventoryAccount,
  CogsResult,
  ReconciliationStateType,
  CashStateType,
  MobileMoneyStateType,
  PayrollWorkerStateType,
  PayslipData,
} from "./tier3";

// ─── Platform Agents ─────────────────────────────────────────────────────────
export {
  reportingAgent,
  documentAgent,
  budgetAgent,
  analyticsAgent,
} from "./platform";
export type {
  ReportingStateType,
  ProfitAndLoss,
  BalanceSheet,
  Narrative,
  DocumentStateType,
  BudgetStateType,
  BudgetItem,
  BudgetSummary,
  AnalyticsStateType,
  FinancialRatio,
  AnalyticsSummary,
} from "./platform";
