/**
 * Artifact Router — tRPC endpoints for the artifact store
 *
 * Artifacts are files generated by agents or users:
 * - Financial reports (P&L, Balance Sheet, Cash Flow)
 * - Data exports (CSV, Excel, PDF)
 * - Generated invoices, credit notes
 * - Tax filings
 *
 * All endpoints are entity-scoped and audit-logged.
 */

import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { router, protectedProcedure } from "@/lib/trpc/server";
import { db } from "@/lib/db";
import { eq, and, desc, sql } from "drizzle-orm";
import { artifactRegistry, auditLog } from "@xenboox/db/schema";
import { getPresignedDownloadUrl, deleteObject } from "@/lib/r2";

// ─── Helpers ────────────────────────────────────────────────────────────────

async function writeAudit(params: {
  entityId: string;
  userId?: string;
  action: string;
  entityIdRef: string;
  newValues?: Record<string, unknown>;
}) {
  await db.insert(auditLog).values({
    entityId: params.entityId,
    userId: params.userId,
    action: params.action,
    entityType: "artifact",
    entityIdRef: params.entityIdRef,
    newValues: params.newValues,
  });
}

// ─── Artifact Router ────────────────────────────────────────────────────────

export const artifactRouter = router({
  /**
   * List all artifacts for the current entity, with optional filters.
   */
  list: protectedProcedure
    .input(
      z.object({
        kind: z
          .enum([
            "report",
            "export",
            "invoice_pdf",
            "credit_note",
            "filing",
            "statement",
            "contract",
            "custom",
          ])
          .optional(),
        status: z
          .enum(["generating", "ready", "expired", "failed", "archived"])
          .optional(),
        limit: z.number().min(1).max(100).default(50),
        offset: z.number().min(0).default(0),
      }),
    )
    .query(async ({ ctx, input }) => {
      const conditions = [eq(artifactRegistry.entityId, ctx.entityId!)];

      if (input.kind) {
        conditions.push(eq(artifactRegistry.kind, input.kind));
      }
      if (input.status) {
        conditions.push(eq(artifactRegistry.status, input.status));
      }

      const results = await db.query.artifactRegistry.findMany({
        where: and(...conditions),
        orderBy: [desc(artifactRegistry.createdAt)],
        limit: input.limit,
        offset: input.offset,
      });

      return results;
    }),

  /**
   * Get a single artifact by ID.
   */
  getById: protectedProcedure
    .input(z.object({ id: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      const artifact = await db.query.artifactRegistry.findFirst({
        where: and(
          eq(artifactRegistry.id, input.id),
          eq(artifactRegistry.entityId, ctx.entityId!),
        ),
      });

      if (!artifact) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Artifact not found",
        });
      }

      return artifact;
    }),

  /**
   * Get a presigned download URL for an artifact.
   * Logs the download in the audit trail.
   */
  download: protectedProcedure
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      const artifact = await db.query.artifactRegistry.findFirst({
        where: and(
          eq(artifactRegistry.id, input.id),
          eq(artifactRegistry.entityId, ctx.entityId!),
        ),
      });

      if (!artifact) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Artifact not found",
        });
      }

      if (artifact.status === "expired") {
        throw new TRPCError({
          code: "GONE",
          message: "This artifact has expired and is no longer available",
        });
      }

      if (artifact.status === "failed") {
        throw new TRPCError({
          code: "INTERNAL_SERVER_ERROR",
          message: "Artifact generation failed — no file available",
        });
      }

      if (!artifact.r2Key) {
        throw new TRPCError({
          code: "BAD_REQUEST",
          message: "Artifact has no storage key",
        });
      }

      const downloadUrl = await getPresignedDownloadUrl(artifact.r2Key);

      // Audit log
      await writeAudit({
        entityId: ctx.entityId!,
        userId: ctx.session!.user!.id!,
        action: "artifact.download",
        entityIdRef: artifact.id,
        newValues: {
          name: artifact.name,
          kind: artifact.kind,
          mimeType: artifact.mimeType,
        },
      });

      return { downloadUrl, mimeType: artifact.mimeType, name: artifact.name };
    }),

  /**
   * Create an artifact record. Called by agents or jobs after generating a file.
   * The file must already be uploaded to R2 before calling this.
   */
  create: protectedProcedure
    .input(
      z.object({
        kind: z.enum([
          "report",
          "export",
          "invoice_pdf",
          "credit_note",
          "filing",
          "statement",
          "contract",
          "custom",
        ]),
        name: z.string().min(1).max(255),
        description: z.string().optional(),
        mimeType: z.string().min(1),
        sizeBytes: z.number().int().min(0).optional(),
        r2Key: z.string().min(1),
        r2Bucket: z.string().min(1),
        sourceDocumentId: z.string().uuid().optional(),
        sourceJournalEntryId: z.string().uuid().optional(),
        parameters: z.record(z.unknown()).optional(),
        ttl: z.number().int().min(0).optional(), // seconds
        metadata: z.record(z.unknown()).optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      // Compute expiration
      let expiresAt: Date | null = null;
      if (input.ttl && input.ttl > 0) {
        expiresAt = new Date(Date.now() + input.ttl * 1000);
      }

      const [artifact] = await db
        .insert(artifactRegistry)
        .values({
          entityId: ctx.entityId!,
          kind: input.kind,
          name: input.name,
          description: input.description,
          mimeType: input.mimeType,
          sizeBytes: input.sizeBytes,
          r2Key: input.r2Key,
          r2Bucket: input.r2Bucket,
          createdBy: ctx.session!.user!.id!,
          createdByName: ctx.session!.user!.name ?? ctx.session!.user!.email,
          sourceDocumentId: input.sourceDocumentId,
          sourceJournalEntryId: input.sourceJournalEntryId,
          parameters: input.parameters,
          ttl: input.ttl,
          expiresAt: expiresAt,
          status: "ready",
          metadata: input.metadata,
        })
        .returning();

      // Audit log
      await writeAudit({
        entityId: ctx.entityId!,
        userId: ctx.session!.user!.id!,
        action: "artifact.create",
        entityIdRef: artifact.id,
        newValues: {
          kind: input.kind,
          name: input.name,
          mimeType: input.mimeType,
        },
      });

      return artifact;
    }),

  /**
   * Delete an artifact (soft-delete by archiving, or hard-delete with R2 removal).
   */
  delete: protectedProcedure
    .input(
      z.object({
        id: z.string().uuid(),
        hardDelete: z.boolean().default(false), // If true, also delete from R2
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const artifact = await db.query.artifactRegistry.findFirst({
        where: and(
          eq(artifactRegistry.id, input.id),
          eq(artifactRegistry.entityId, ctx.entityId!),
        ),
      });

      if (!artifact) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Artifact not found",
        });
      }

      if (input.hardDelete && artifact.r2Key) {
        // Delete from R2
        try {
          await deleteObject(artifact.r2Key);
        } catch {
          // R2 delete failure shouldn't block DB deletion
          console.warn(
            `[artifact] Failed to delete R2 object: ${artifact.r2Key}`,
          );
        }
      }

      // Delete from DB
      await db
        .delete(artifactRegistry)
        .where(eq(artifactRegistry.id, input.id));

      // Audit log
      await writeAudit({
        entityId: ctx.entityId!,
        userId: ctx.session!.user!.id!,
        action: input.hardDelete ? "artifact.hard_delete" : "artifact.delete",
        entityIdRef: artifact.id,
        newValues: {
          name: artifact.name,
          kind: artifact.kind,
          hardDelete: input.hardDelete,
        },
      });

      return { success: true };
    }),

  /**
   * Get artifact counts by kind for the current entity.
   * Useful for dashboard summary cards.
   */
  getSummary: protectedProcedure.query(async ({ ctx }) => {
    const artifacts = await db.query.artifactRegistry.findMany({
      where: eq(artifactRegistry.entityId, ctx.entityId!),
      columns: { kind: true, status: true, sizeBytes: true },
    });

    const byKind: Record<string, number> = {};
    const byStatus: Record<string, number> = {};
    let totalSize = 0;

    for (const a of artifacts) {
      byKind[a.kind] = (byKind[a.kind] ?? 0) + 1;
      byStatus[a.status] = (byStatus[a.status] ?? 0) + 1;
      totalSize += a.sizeBytes ?? 0;
    }

    return {
      total: artifacts.length,
      totalSize,
      byKind,
      byStatus,
    };
  }),
});
