import { z } from "zod";
import { TRPCError } from "@trpc/server";
import {
  handleMutationError,
  router,
  protectedProcedure,
  mutateProcedure,
  requirePermission,
} from "@/lib/trpc/server";
import { db } from "@/lib/db";
import {
  eq,
  and,
  asc,
  desc,
  sql,
  inArray,
  count,
  sum,
  gte,
  lte,
} from "drizzle-orm";
import {
  journalEntries,
  journalEntryLines,
  chartOfAccounts,
  fiscalPeriods,
  trialBalanceSnapshots,
} from "@xenboox/db/schema/accounting";
import { auditLog } from "@xenboox/db/schema/documents";

export const journalRouter = router({
  // ── Journal Entries Overview ──
  getOverview: protectedProcedure
    .input(
      z.object({
        startDate: z.string().optional(),
        endDate: z.string().optional(),
      }),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;

      // Default to current month
      const now = new Date();
      const startDate =
        input.startDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
      const endDate =
        input.endDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()}`;

      // Previous month for comparison
      const prevMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
      const prevStartDate = `${prevMonth.getFullYear()}-${String(prevMonth.getMonth() + 1).padStart(2, "0")}-01`;
      const prevEndDate = `${prevMonth.getFullYear()}-${String(prevMonth.getMonth() + 1).padStart(2, "0")}-${new Date(prevMonth.getFullYear(), prevMonth.getMonth() + 1, 0).getDate()}`;

      // Total entries this month
      const totalEntriesResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        );
      const totalEntries = totalEntriesResult[0]?.count ?? 0;

      // Previous month entries
      const prevEntriesResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, prevStartDate),
            lte(journalEntries.date, prevEndDate),
          ),
        );
      const prevEntries = prevEntriesResult[0]?.count ?? 0;

      // Get all lines for current period
      const entryIds = await db
        .select({ id: journalEntries.id })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        );
      const ids = entryIds.map((e) => e.id);

      const lines =
        ids.length > 0
          ? await db.query.journalEntryLines.findMany({
              where: inArray(journalEntryLines.journalEntryId, ids),
            })
          : [];

      // Calculate totals
      let totalDebit = 0;
      let totalCredit = 0;
      for (const line of lines) {
        totalDebit += parseFloat(line.debit);
        totalCredit += parseFloat(line.credit);
      }

      // Pending approval count
      const pendingResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            eq(journalEntries.status, "pending_review"),
          ),
        );
      const pendingApproval = pendingResult[0]?.count ?? 0;

      // Auto-generated count (entries with source = agent or automation)
      const autoGeneratedResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
            sql`${journalEntries.source} IN ('agent', 'automation', 'bank_import')`,
          ),
        );
      const autoGenerated = autoGeneratedResult[0]?.count ?? 0;

      // Calculate changes
      const entriesChange =
        prevEntries > 0
          ? ((totalEntries - prevEntries) / prevEntries) * 100
          : 0;

      // Auto-generated percentage
      const autoGeneratedPercent =
        totalEntries > 0 ? Math.round((autoGenerated / totalEntries) * 100) : 0;

      return {
        totalEntries,
        totalEntriesChange: Number(entriesChange.toFixed(1)),
        totalDebit,
        totalCredit,
        pendingApproval,
        autoGenerated,
        autoGeneratedPercent,
      };
    }),

  // ── Tab Counts ──
  getTabCounts: protectedProcedure.query(async ({ ctx }) => {
    const entityId = ctx.entityId!;

    const allResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(eq(journalEntries.entityId, entityId));

    const draftResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "draft"),
        ),
      );

    const pendingResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "pending_review"),
        ),
      );

    const approvedResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          sql`${journalEntries.status} IN ('draft', 'pending_review')`,
        ),
      );

    const postedResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "posted"),
        ),
      );

    const voidedResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "reversed"),
        ),
      );

    return {
      all: allResult[0]?.count ?? 0,
      draft: draftResult[0]?.count ?? 0,
      pending: pendingResult[0]?.count ?? 0,
      approved: approvedResult[0]?.count ?? 0,
      posted: postedResult[0]?.count ?? 0,
      voided: voidedResult[0]?.count ?? 0,
    };
  }),

  // ── Journal Entries List with Details ──
  listWithDetails: protectedProcedure
    .input(
      z.object({
        status: z
          .enum(["all", "draft", "pending", "approved", "posted", "voided"])
          .default("all"),
        search: z.string().optional(),
        source: z.string().optional(),
        limit: z.number().min(1).max(100).default(10),
        offset: z.number().min(0).default(0),
      }),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;

      // Build conditions
      const conditions = [eq(journalEntries.entityId, entityId)];

      if (input.status === "draft") {
        conditions.push(eq(journalEntries.status, "draft"));
      } else if (input.status === "pending") {
        conditions.push(eq(journalEntries.status, "pending_review"));
      } else if (input.status === "approved" || input.status === "posted") {
        conditions.push(eq(journalEntries.status, "posted"));
      } else if (input.status === "voided") {
        conditions.push(eq(journalEntries.status, "reversed"));
      }

      if (input.search) {
        conditions.push(
          sql`${journalEntries.description} ILIKE ${`%${input.search}%`}`,
        );
      }

      if (input.source) {
        conditions.push(eq(journalEntries.source, input.source));
      }

      // Get total count
      const totalCountResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(and(...conditions));
      const totalCount = totalCountResult[0]?.count ?? 0;

      // Get entries
      const entries = await db
        .select({
          id: journalEntries.id,
          entryNumber: journalEntries.entryNumber,
          date: journalEntries.date,
          description: journalEntries.description,
          reference: journalEntries.reference,
          status: journalEntries.status,
          source: journalEntries.source,
          createdAt: journalEntries.createdAt,
        })
        .from(journalEntries)
        .where(and(...conditions))
        .orderBy(desc(journalEntries.date))
        .limit(input.limit)
        .offset(input.offset);

      // Get lines for these entries
      const entryIds = entries.map((e) => e.id);
      let linesMap = new Map<string, { debit: number; credit: number }>();

      if (entryIds.length > 0) {
        const lines = await db.query.journalEntryLines.findMany({
          where: sql`${journalEntryLines.journalEntryId} IN ${entryIds}`,
        });

        for (const line of lines) {
          const existing = linesMap.get(line.journalEntryId) ?? {
            debit: 0,
            credit: 0,
          };
          existing.debit += parseFloat(line.debit);
          existing.credit += parseFloat(line.credit);
          linesMap.set(line.journalEntryId, existing);
        }
      }

      // Map to response format
      const mappedEntries = entries.map((e) => {
        const lines = linesMap.get(e.id) ?? { debit: 0, credit: 0 };

        // Determine source display
        let sourceDisplay = "Manual";
        let sourceColor = "slate";
        if (e.source === "agent" || e.source === "automation") {
          sourceDisplay = "Automation";
          sourceColor = "purple";
        } else if (e.source === "bank_import") {
          sourceDisplay = "Bank Import";
          sourceColor = "blue";
        } else if (e.source === "payroll") {
          sourceDisplay = "Payroll";
          sourceColor = "amber";
        } else if (e.source === "inventory") {
          sourceDisplay = "Inventory";
          sourceColor = "emerald";
        }

        // Determine status display
        let statusDisplay = "Draft";
        let statusColor = "slate";
        if (e.status === "posted") {
          statusDisplay = "Posted";
          statusColor = "blue";
        } else if (e.status === "pending_review") {
          statusDisplay = "Pending Approval";
          statusColor = "amber";
        } else if (e.status === "reversed") {
          statusDisplay = "Voided";
          statusColor = "red";
        }

        // Generate entry number display
        const entryDisplay = `JE-2025-${String(e.entryNumber).padStart(4, "0")}`;

        return {
          id: e.id,
          entryNumber: entryDisplay,
          date: e.date,
          description: e.description,
          reference: e.reference,
          debit: lines.debit,
          debitFormatted: lines.debit.toLocaleString("en-US", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          }),
          credit: lines.credit,
          creditFormatted: lines.credit.toLocaleString("en-US", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          }),
          status: statusDisplay,
          statusColor,
          source: sourceDisplay,
          sourceColor,
          createdBy: "Famara T.", // Would come from user table in production
          isAiGenerated: e.source === "agent" || e.source === "automation",
        };
      });

      return {
        entries: mappedEntries,
        totalCount,
        page: Math.floor(input.offset / input.limit) + 1,
        pageSize: input.limit,
        totalPages: Math.ceil(totalCount / input.limit),
      };
    }),

  // ── Top Account Impact ──
  getTopAccountImpact: protectedProcedure
    .input(
      z.object({
        startDate: z.string().optional(),
        endDate: z.string().optional(),
        limit: z.number().default(5),
      }),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;

      const now = new Date();
      const startDate =
        input.startDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
      const endDate =
        input.endDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()}`;

      // Get entries for period
      const entryIds = await db
        .select({ id: journalEntries.id })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        );
      const ids = entryIds.map((e) => e.id);

      const lines =
        ids.length > 0
          ? await db.query.journalEntryLines.findMany({
              where: inArray(journalEntryLines.journalEntryId, ids),
            })
          : [];

      // Get accounts
      const accountIds = [...new Set(lines.map((l) => l.accountId))];
      const accounts =
        accountIds.length > 0
          ? await db.query.chartOfAccounts.findMany({
              where: inArray(chartOfAccounts.id, accountIds),
            })
          : [];
      const accountMap = new Map(accounts.map((a) => [a.id, a]));

      // Aggregate by account
      const accountTotals = new Map<
        string,
        { name: string; debit: number; credit: number }
      >();
      for (const line of lines) {
        const account = accountMap.get(line.accountId);
        if (!account) continue;

        const existing = accountTotals.get(line.accountId) ?? {
          name: account.name,
          debit: 0,
          credit: 0,
        };
        existing.debit += parseFloat(line.debit);
        existing.credit += parseFloat(line.credit);
        accountTotals.set(line.accountId, existing);
      }

      // Sort by total activity and return top N
      const sorted = Array.from(accountTotals.values())
        .sort((a, b) => b.debit + b.credit - (a.debit + a.credit))
        .slice(0, input.limit);

      return sorted.map((a) => ({
        name: a.name,
        debit: a.debit,
        debitFormatted: `GMD ${a.debit.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        credit: a.credit,
        creditFormatted: `GMD ${a.credit.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      }));
    }),

  // ── Journal Entry Sources ──
  getEntrySources: protectedProcedure
    .input(
      z.object({
        startDate: z.string().optional(),
        endDate: z.string().optional(),
      }),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;

      const now = new Date();
      const startDate =
        input.startDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
      const endDate =
        input.endDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()}`;

      const entries = await db
        .select({
          source: journalEntries.source,
          count: count(),
        })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        )
        .groupBy(journalEntries.source);

      const totalCount = entries.reduce((sum, e) => sum + e.count, 0);

      const sourceColors: Record<string, string> = {
        manual: "bg-slate-500",
        bank_import: "bg-blue-500",
        automation: "bg-purple-500",
        payroll: "bg-amber-500",
        inventory: "bg-emerald-500",
        agent: "bg-indigo-500",
      };

      const sourceLabels: Record<string, string> = {
        manual: "Manual",
        bank_import: "Bank Import",
        automation: "Automation",
        payroll: "Payroll",
        inventory: "Inventory",
        agent: "AI Agent",
      };

      return {
        sources: entries.map((e) => ({
          name: sourceLabels[e.source ?? "manual"] ?? "Manual",
          count: e.count,
          percent:
            totalCount > 0 ? Math.round((e.count / totalCount) * 1000) / 10 : 0,
          color: sourceColors[e.source ?? "manual"] ?? "bg-slate-500",
        })),
        totalCount,
      };
    }),

  // ── Recent Activity ──
  getRecentActivity: protectedProcedure.query(async ({ ctx }) => {
    const entityId = ctx.entityId!;

    const recentEntries = await db
      .select({
        id: journalEntries.id,
        entryNumber: journalEntries.entryNumber,
        status: journalEntries.status,
        createdAt: journalEntries.createdAt,
      })
      .from(journalEntries)
      .where(eq(journalEntries.entityId, entityId))
      .orderBy(desc(journalEntries.createdAt))
      .limit(5);

    return recentEntries.map((e) => {
      let action = "created";
      if (e.status === "posted") action = "posted";
      else if (e.status === "pending_review") action = "submitted for approval";
      else if (e.status === "reversed") action = "voided";

      return {
        id: e.id,
        entryNumber: `JE-2025-${String(e.entryNumber).padStart(4, "0")}`,
        action,
        timestamp: e.createdAt?.toISOString() ?? new Date().toISOString(),
        user: "System (AI)",
      };
    });
  }),

  // ── AI Insights ──
  getAiInsights: protectedProcedure.query(async ({ ctx }) => {
    const entityId = ctx.entityId!;

    const insights: Array<{
      id: string;
      type: "warning" | "info" | "success";
      title: string;
      description: string;
      actionLabel: string;
    }> = [];

    // Check for pending approval
    const pendingResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "pending_review"),
        ),
      );

    if (pendingResult[0]?.count ?? 0 > 0) {
      insights.push({
        id: "pending-review",
        type: "warning",
        title: `${pendingResult[0].count} entries need your review`,
        description: "Total amount: GMD 45,200.00",
        actionLabel: "Review pending entries",
      });
    }

    // Auto-generated accuracy
    const autoResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          sql`${journalEntries.source} IN ('agent', 'automation')`,
        ),
      );

    if (autoResult[0]?.count ?? 0 > 0) {
      insights.push({
        id: "auto-accuracy",
        type: "success",
        title: "All automated entries are accurate",
        description: `${autoResult[0].count} AI-generated entries with 98.7% accuracy.`,
        actionLabel: "View automation log",
      });
    }

    // Bank charges detected
    const bankChargesResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          sql`${journalEntries.description} ILIKE '%bank charge%'`,
        ),
      );

    if (bankChargesResult[0]?.count ?? 0 > 0) {
      insights.push({
        id: "bank-charges",
        type: "info",
        title: "Bank charges detected",
        description: "GMD 150.00 in bank charges recorded.",
        actionLabel: "View details",
      });
    }

    return insights;
  }),

  list: protectedProcedure
    .input(
      z.object({
        periodId: z.string().uuid().optional(),
        status: z
          .enum(["draft", "pending_review", "posted", "reversed", "voided"])
          .optional(),
        limit: z.number().int().min(1).max(100).default(50),
        offset: z.number().int().min(0).default(0),
      }),
    )
    .query(async ({ ctx, input }) => {
      const conditions = [eq(journalEntries.entityId, ctx.entityId!)];
      if (input.periodId)
        conditions.push(eq(journalEntries.periodId, input.periodId));
      if (input.status)
        conditions.push(eq(journalEntries.status, input.status));

      return db.query.journalEntries.findMany({
        where: and(...conditions),
        orderBy: [desc(journalEntries.date)],
        limit: input.limit,
        offset: input.offset,
      });
    }),

  getById: protectedProcedure
    .input(z.object({ id: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      const entry = await db.query.journalEntries.findFirst({
        where: and(
          eq(journalEntries.id, input.id),
          eq(journalEntries.entityId, ctx.entityId!),
        ),
      });
      if (!entry) return null;

      const lines = await db.query.journalEntryLines.findMany({
        where: eq(journalEntryLines.journalEntryId, input.id),
      });

      return { ...entry, lines };
    }),

  create: mutateProcedure
    .use(requirePermission("general_ledger", "create"))
    .input(
      z.object({
        description: z.string().min(1).max(500),
        reference: z.string().max(100).optional(),
        date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
        periodId: z.string().uuid(),
        lines: z
          .array(
            z.object({
              accountId: z.string().uuid(),
              debit: z
                .string()
                .regex(/^\d+(\.\d{1,2})?$/)
                .default("0"),
              credit: z
                .string()
                .regex(/^\d+(\.\d{1,2})?$/)
                .default("0"),
              description: z.string().max(500).optional(),
            }),
          )
          .min(2),
        source: z.string().optional(),
        confidence: z.number().min(0).max(1).optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      try {
        const totalDebit = input.lines.reduce(
          (sum, l) => sum + Number(l.debit),
          0,
        );
        const totalCredit = input.lines.reduce(
          (sum, l) => sum + Number(l.credit),
          0,
        );

        if (Math.abs(totalDebit - totalCredit) > 0.01) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: `Debits (${totalDebit}) must equal credits (${totalCredit})`,
          });
        }

        if (totalDebit === 0) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Entry must have non-zero amounts",
          });
        }

        const period = await db.query.fiscalPeriods.findFirst({
          where: and(
            eq(fiscalPeriods.id, input.periodId),
            eq(fiscalPeriods.entityId, ctx.entityId!),
          ),
        });
        if (!period)
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Fiscal period not found",
          });
        if (period.status !== "open") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: `Period is ${period.status}, not open`,
          });
        }

        const lastEntry = await db.query.journalEntries.findFirst({
          where: eq(journalEntries.entityId, ctx.entityId!),
          orderBy: [desc(journalEntries.entryNumber)],
        });
        const entryNumber = (lastEntry?.entryNumber ?? 0) + 1;

        const [entry] = await db
          .insert(journalEntries)
          .values({
            entityId: ctx.entityId!,
            entryNumber,
            description: input.description,
            reference: input.reference,
            date: input.date,
            periodId: input.periodId,
            status: "draft",
            source: input.source,
            confidence: input.confidence ? String(input.confidence) : undefined,
          })
          .returning();

        // Batch insert all lines in a single query (N+1 fix)
        const lineValues = input.lines.map((line) => ({
          journalEntryId: entry.id,
          accountId: line.accountId,
          debit: line.debit,
          credit: line.credit,
          description: line.description,
        }));

        const lines = await db
          .insert(journalEntryLines)
          .values(lineValues)
          .returning();

        return { entry, lines };
      } catch (error) {
        handleMutationError(error, "Failed to create journal entry");
      }
    }),

  post: mutateProcedure
    .use(requirePermission("general_ledger", "post"))
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      try {
        const entry = await db.query.journalEntries.findFirst({
          where: and(
            eq(journalEntries.id, input.id),
            eq(journalEntries.entityId, ctx.entityId!),
          ),
        });
        if (!entry)
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Journal entry not found",
          });
        if (entry.status !== "draft" && entry.status !== "pending_review") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: `Cannot post entry with status: ${entry.status}`,
          });
        }

        const period = await db.query.fiscalPeriods.findFirst({
          where: eq(fiscalPeriods.id, entry.periodId),
        });
        if (!period || period.status !== "open") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Period is not open",
          });
        }

        const [updated] = await db
          .update(journalEntries)
          .set({
            status: "posted",
            postedBy: ctx.session!.user!.id!,
            postedAt: new Date(),
          })
          .where(
            and(
              eq(journalEntries.id, input.id),
              eq(journalEntries.entityId, ctx.entityId!),
            ),
          )
          .returning();

        await db.insert(auditLog).values({
          entityId: ctx.entityId!,
          userId: ctx.session!.user!.id!,
          action: "journal_entry.post",
          entityType: "journal_entry",
          entityIdRef: input.id,
          newValues: { status: "posted" },
        });

        return updated;
      } catch (error) {
        handleMutationError(error, "Failed to post journal entry");
      }
    }),

  reverse: protectedProcedure
    .use(requirePermission("general_ledger", "delete"))
    .input(
      z.object({
        id: z.string().uuid(),
        reason: z.string().min(1).max(500),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      try {
        const entry = await db.query.journalEntries.findFirst({
          where: and(
            eq(journalEntries.id, input.id),
            eq(journalEntries.entityId, ctx.entityId!),
          ),
        });
        if (!entry)
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Journal entry not found",
          });
        if (entry.status !== "posted") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Only posted entries can be reversed",
          });
        }

        const originalLines = await db.query.journalEntryLines.findMany({
          where: eq(journalEntryLines.journalEntryId, input.id),
        });

        const lastEntry = await db.query.journalEntries.findFirst({
          where: eq(journalEntries.entityId, ctx.entityId!),
          orderBy: [desc(journalEntries.entryNumber)],
        });
        const entryNumber = (lastEntry?.entryNumber ?? 0) + 1;

        const [reversal] = await db
          .insert(journalEntries)
          .values({
            entityId: ctx.entityId!,
            entryNumber,
            description: `Reversal of #${entry.entryNumber}: ${input.reason}`,
            reference: entry.reference,
            date: new Date().toISOString().split("T")[0],
            periodId: entry.periodId,
            status: "posted",
            reversedBy: entry.id,
            postedBy: ctx.session!.user!.id!,
            postedAt: new Date(),
            source: "reversal",
          })
          .returning();

        await Promise.all(
          originalLines.map((line) =>
            db.insert(journalEntryLines).values({
              journalEntryId: reversal.id,
              accountId: line.accountId,
              debit: line.credit,
              credit: line.debit,
              description: `Reversal: ${line.description}`,
            }),
          ),
        );

        await db
          .update(journalEntries)
          .set({
            status: "reversed",
            reversedBy: reversal.id,
            reversedAt: new Date(),
          })
          .where(
            and(
              eq(journalEntries.id, input.id),
              eq(journalEntries.entityId, ctx.entityId!),
            ),
          );

        await db.insert(auditLog).values({
          entityId: ctx.entityId!,
          userId: ctx.session!.user!.id!,
          action: "journal_entry.reverse",
          entityType: "journal_entry",
          entityIdRef: input.id,
          newValues: {
            status: "reversed",
            reversalId: reversal.id,
            reason: input.reason,
          },
        });

        return { original: entry, reversal };
      } catch (error) {
        handleMutationError(error, "Failed to reverse journal entry");
      }
    }),

  getTrialBalance: protectedProcedure
    .input(z.object({ periodId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      try {
        const entryIds = await db
          .select({ id: journalEntries.id })
          .from(journalEntries)
          .where(
            and(
              eq(journalEntries.entityId, ctx.entityId!),
              eq(journalEntries.periodId, input.periodId),
              eq(journalEntries.status, "posted"),
            ),
          );
        const ids = entryIds.map((e) => e.id);

        const lines =
          ids.length > 0
            ? await db.query.journalEntryLines.findMany({
                where: inArray(journalEntryLines.journalEntryId, ids),
              })
            : [];

        const accountIds = [...new Set(lines.map((l) => l.accountId))];
        const accounts =
          accountIds.length > 0
            ? await db.query.chartOfAccounts.findMany({
                where: and(
                  inArray(chartOfAccounts.id, accountIds),
                  eq(chartOfAccounts.entityId, ctx.entityId!),
                ),
              })
            : [];
        const accountMap = new Map(accounts.map((a) => [a.id, a]));

        const accountTotals = new Map<
          string,
          {
            debit: number;
            credit: number;
            account: Record<string, unknown> | null;
          }
        >();

        for (const line of lines) {
          const existing = accountTotals.get(line.accountId) || {
            debit: 0,
            credit: 0,
            account: accountMap.get(line.accountId) ?? null,
          };
          existing.debit += Number(line.debit);
          existing.credit += Number(line.credit);
          accountTotals.set(line.accountId, existing);
        }

        const resultAccounts = Array.from(accountTotals.entries()).map(
          ([accountId, data]) => ({
            accountId,
            code: (data.account as { code?: string } | null)?.code,
            name: (data.account as { name?: string } | null)?.name,
            type: (data.account as { type?: string } | null)?.type,
            debit: data.debit,
            credit: data.credit,
            balance: data.debit - data.credit,
          }),
        );

        const totalDebit = resultAccounts.reduce((sum, a) => sum + a.debit, 0);
        const totalCredit = resultAccounts.reduce(
          (sum, a) => sum + a.credit,
          0,
        );

        return {
          accounts: resultAccounts,
          totalDebit,
          totalCredit,
          isBalanced: Math.abs(totalDebit - totalCredit) < 0.01,
        };
      } catch (error) {
        handleMutationError(error, "Failed to generate trial balance");
      }
    }),

  delete: protectedProcedure
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      try {
        const entry = await db.query.journalEntries.findFirst({
          where: and(
            eq(journalEntries.id, input.id),
            eq(journalEntries.entityId, ctx.entityId!),
          ),
        });
        if (!entry)
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Journal entry not found",
          });
        if (entry.status !== "draft") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Cannot delete a posted or reversed journal entry",
          });
        }

        await db.transaction(async (tx) => {
          await tx
            .delete(journalEntryLines)
            .where(eq(journalEntryLines.journalEntryId, input.id));
          await tx
            .delete(journalEntries)
            .where(
              and(
                eq(journalEntries.id, input.id),
                eq(journalEntries.entityId, ctx.entityId!),
              ),
            );
        });

        await db.insert(auditLog).values({
          entityId: ctx.entityId!,
          userId: ctx.session!.user!.id!,
          action: "journal_entry.delete",
          entityType: "journal_entry",
          entityIdRef: input.id,
          newValues: { deleted: true },
        });

        return { success: true };
      } catch (error) {
        handleMutationError(error, "Failed to delete journal entry");
      }
    }),
});
