import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { eq, and, desc, sql, inArray, count, gte, lte } from "drizzle-orm";
import {
  journalEntries,
  journalEntryLines,
  chartOfAccounts,
  fiscalPeriods,
} from "@xenboox/db/schema/accounting";
import { auditLog } from "@xenboox/db/schema/documents";
import {
  validateJournalEntry,
  validateForPosting,
  logTrustGuardResult,
  trustGuardToError,
} from "@xenboox/agents";

import { db } from "@/lib/db";
import {
  handleMutationError,
  router,
  rlsProtectedProcedure,
  rlsMutateProcedure,
  requirePermission,
} from "@/lib/trpc/server";
import { dispatchWebhookEvent } from "@/lib/webhooks/delivery";
import { logger } from "@/lib/logger";

export const journalRouter = router({
  // ── Journal Entries Overview ──
  getOverview: rlsProtectedProcedure
    .input(
      z.object({
        startDate: z.string().optional(),
        endDate: z.string().optional(),
      }),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;

      // Default to current month
      const now = new Date();
      const startDate =
        input.startDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
      const endDate =
        input.endDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()}`;

      // Previous month for comparison
      const prevMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
      const prevStartDate = `${prevMonth.getFullYear()}-${String(prevMonth.getMonth() + 1).padStart(2, "0")}-01`;
      const prevEndDate = `${prevMonth.getFullYear()}-${String(prevMonth.getMonth() + 1).padStart(2, "0")}-${new Date(prevMonth.getFullYear(), prevMonth.getMonth() + 1, 0).getDate()}`;

      // Total entries this month
      const totalEntriesResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        );
      const totalEntries = totalEntriesResult[0]?.count ?? 0;

      // Previous month entries
      const prevEntriesResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, prevStartDate),
            lte(journalEntries.date, prevEndDate),
          ),
        );
      const prevEntries = prevEntriesResult[0]?.count ?? 0;

      // Get all lines for current period
      const entryIds = await db
        .select({ id: journalEntries.id })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        );
      const ids = entryIds.map((e) => e.id);

      const lines =
        ids.length > 0
          ? await db.query.journalEntryLines.findMany({
              where: inArray(journalEntryLines.journalEntryId, ids),
            })
          : [];

      // Calculate totals
      let totalDebit = 0;
      let totalCredit = 0;
      for (const line of lines) {
        totalDebit += parseFloat(line.debit ?? "0");
        totalCredit += parseFloat(line.credit ?? "0");
      }

      // Pending approval count
      const pendingResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            eq(journalEntries.status, "pending_review"),
          ),
        );
      const pendingApproval = pendingResult[0]?.count ?? 0;

      // Auto-generated count (entries with source = agent or automation)
      const autoGeneratedResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
            sql`${journalEntries.source} IN ('agent', 'automation', 'bank_import')`,
          ),
        );
      const autoGenerated = autoGeneratedResult[0]?.count ?? 0;

      // Calculate changes
      const entriesChange =
        prevEntries > 0
          ? ((totalEntries - prevEntries) / prevEntries) * 100
          : 0;

      // Auto-generated percentage
      const autoGeneratedPercent =
        totalEntries > 0 ? Math.round((autoGenerated / totalEntries) * 100) : 0;

      return {
        totalEntries,
        totalEntriesChange: Number(entriesChange.toFixed(1)),
        totalDebit,
        totalCredit,
        pendingApproval,
        autoGenerated,
        autoGeneratedPercent,
      };
    }),

  // ── Tab Counts ──
  getTabCounts: rlsProtectedProcedure.query(async ({ ctx }) => {
    const entityId = ctx.entityId!;

    const allResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(eq(journalEntries.entityId, entityId));

    const draftResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "draft"),
        ),
      );

    const pendingResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "pending_review"),
        ),
      );

    const approvedResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          sql`${journalEntries.status} IN ('draft', 'pending_review')`,
        ),
      );

    const postedResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "posted"),
        ),
      );

    const voidedResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "reversed"),
        ),
      );

    return {
      all: allResult[0]?.count ?? 0,
      draft: draftResult[0]?.count ?? 0,
      pending: pendingResult[0]?.count ?? 0,
      approved: approvedResult[0]?.count ?? 0,
      posted: postedResult[0]?.count ?? 0,
      voided: voidedResult[0]?.count ?? 0,
    };
  }),

  // ── Journal Entries List with Details ──
  listWithDetails: rlsProtectedProcedure
    .input(
      z.object({
        status: z
          .enum(["all", "draft", "pending", "approved", "posted", "voided"])
          .default("all"),
        search: z.string().optional(),
        source: z.string().optional(),
        limit: z.number().min(1).max(100).default(10),
        offset: z.number().min(0).default(0),
      }),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;

      // Build conditions
      const conditions = [eq(journalEntries.entityId, entityId)];

      if (input.status === "draft") {
        conditions.push(eq(journalEntries.status, "draft"));
      } else if (input.status === "pending") {
        conditions.push(eq(journalEntries.status, "pending_review"));
      } else if (input.status === "approved" || input.status === "posted") {
        conditions.push(eq(journalEntries.status, "posted"));
      } else if (input.status === "voided") {
        conditions.push(eq(journalEntries.status, "reversed"));
      }

      if (input.search) {
        conditions.push(
          sql`${journalEntries.description} ILIKE ${`%${input.search}%`}`,
        );
      }

      if (input.source) {
        conditions.push(eq(journalEntries.source, input.source));
      }

      // Get total count
      const totalCountResult = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(and(...conditions));
      const totalCount = totalCountResult[0]?.count ?? 0;

      // Get entries
      const entries = await db
        .select({
          id: journalEntries.id,
          entryNumber: journalEntries.entryNumber,
          date: journalEntries.date,
          description: journalEntries.description,
          reference: journalEntries.reference,
          status: journalEntries.status,
          source: journalEntries.source,
          createdAt: journalEntries.createdAt,
        })
        .from(journalEntries)
        .where(and(...conditions))
        .orderBy(desc(journalEntries.date))
        .limit(input.limit)
        .offset(input.offset);

      // Get lines for these entries
      const entryIds = entries.map((e) => e.id);
      const linesMap = new Map<string, { debit: number; credit: number }>();

      if (entryIds.length > 0) {
        const lines = await db.query.journalEntryLines.findMany({
          where: sql`${journalEntryLines.journalEntryId} IN ${entryIds}`,
        });

        for (const line of lines) {
          const existing = linesMap.get(line.journalEntryId) ?? {
            debit: 0,
            credit: 0,
          };
          existing.debit += parseFloat(line.debit ?? "0");
          existing.credit += parseFloat(line.credit ?? "0");
          linesMap.set(line.journalEntryId, existing);
        }
      }

      // Map to response format
      const mappedEntries = entries.map((e) => {
        const lines = linesMap.get(e.id) ?? { debit: 0, credit: 0 };

        // Determine source display
        let sourceDisplay = "Manual";
        let sourceColor = "slate";
        if (e.source === "agent" || e.source === "automation") {
          sourceDisplay = "Automation";
          sourceColor = "purple";
        } else if (e.source === "bank_import") {
          sourceDisplay = "Bank Import";
          sourceColor = "blue";
        } else if (e.source === "payroll") {
          sourceDisplay = "Payroll";
          sourceColor = "amber";
        } else if (e.source === "inventory") {
          sourceDisplay = "Inventory";
          sourceColor = "emerald";
        }

        // Determine status display
        let statusDisplay = "Draft";
        let statusColor = "slate";
        if (e.status === "posted") {
          statusDisplay = "Posted";
          statusColor = "blue";
        } else if (e.status === "pending_review") {
          statusDisplay = "Pending Approval";
          statusColor = "amber";
        } else if (e.status === "reversed") {
          statusDisplay = "Voided";
          statusColor = "red";
        }

        // Generate entry number display
        const entryDisplay = `JE-${new Date().getFullYear()}-${String(e.entryNumber).padStart(4, "0")}`;

        return {
          id: e.id,
          entryNumber: entryDisplay,
          date: e.date,
          description: e.description,
          reference: e.reference,
          debit: lines.debit,
          debitFormatted: lines.debit.toLocaleString("en-US", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          }),
          credit: lines.credit,
          creditFormatted: lines.credit.toLocaleString("en-US", {
            minimumFractionDigits: 2,
            maximumFractionDigits: 2,
          }),
          status: statusDisplay,
          statusColor,
          source: sourceDisplay,
          sourceColor,
          createdBy:
            ctx.session!.user!.name ?? ctx.session!.user!.email ?? "System",
          isAiGenerated: e.source === "agent" || e.source === "automation",
        };
      });

      return {
        entries: mappedEntries,
        totalCount,
        page: Math.floor(input.offset / input.limit) + 1,
        pageSize: input.limit,
        totalPages: Math.ceil(totalCount / input.limit),
      };
    }),

  // ── Top Account Impact ──
  getTopAccountImpact: rlsProtectedProcedure
    .input(
      z.object({
        startDate: z.string().optional(),
        endDate: z.string().optional(),
        limit: z.number().default(5),
      }),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;

      const now = new Date();
      const startDate =
        input.startDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
      const endDate =
        input.endDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()}`;

      // Get entries for period
      const entryIds = await db
        .select({ id: journalEntries.id })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        );
      const ids = entryIds.map((e) => e.id);

      const lines =
        ids.length > 0
          ? await db.query.journalEntryLines.findMany({
              where: inArray(journalEntryLines.journalEntryId, ids),
            })
          : [];

      // Get accounts
      const accountIds = [...new Set(lines.map((l) => l.accountId))];
      const accounts =
        accountIds.length > 0
          ? await db.query.chartOfAccounts.findMany({
              where: inArray(chartOfAccounts.id, accountIds),
            })
          : [];
      const accountMap = new Map(accounts.map((a) => [a.id, a]));

      // Aggregate by account
      const accountTotals = new Map<
        string,
        { name: string; debit: number; credit: number }
      >();
      for (const line of lines) {
        const account = accountMap.get(line.accountId);
        if (!account) continue;

        const existing = accountTotals.get(line.accountId) ?? {
          name: account.name,
          debit: 0,
          credit: 0,
        };
        existing.debit += parseFloat(line.debit ?? "0");
        existing.credit += parseFloat(line.credit ?? "0");
        accountTotals.set(line.accountId, existing);
      }

      // Sort by total activity and return top N
      const sorted = Array.from(accountTotals.values())
        .sort((a, b) => b.debit + b.credit - (a.debit + a.credit))
        .slice(0, input.limit);

      return sorted.map((a) => ({
        name: a.name,
        debit: a.debit,
        debitFormatted: `GMD ${a.debit.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
        credit: a.credit,
        creditFormatted: `GMD ${a.credit.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`,
      }));
    }),

  // ── Journal Entry Sources ──
  getEntrySources: rlsProtectedProcedure
    .input(
      z.object({
        startDate: z.string().optional(),
        endDate: z.string().optional(),
      }),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;

      const now = new Date();
      const startDate =
        input.startDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
      const endDate =
        input.endDate ||
        `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-${new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate()}`;

      const entries = await db
        .select({
          source: journalEntries.source,
          count: count(),
        })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        )
        .groupBy(journalEntries.source);

      const totalCount = entries.reduce((sum, e) => sum + e.count, 0);

      const sourceColors: Record<string, string> = {
        manual: "bg-slate-500",
        bank_import: "bg-blue-500",
        automation: "bg-purple-500",
        payroll: "bg-amber-500",
        inventory: "bg-emerald-500",
        agent: "bg-indigo-500",
      };

      const sourceLabels: Record<string, string> = {
        manual: "Manual",
        bank_import: "Bank Import",
        automation: "Automation",
        payroll: "Payroll",
        inventory: "Inventory",
        agent: "AI Agent",
      };

      return {
        sources: entries.map((e) => ({
          name: sourceLabels[e.source ?? "manual"] ?? "Manual",
          count: e.count,
          percent:
            totalCount > 0 ? Math.round((e.count / totalCount) * 1000) / 10 : 0,
          color: sourceColors[e.source ?? "manual"] ?? "bg-slate-500",
        })),
        totalCount,
      };
    }),

  // ── Recent Activity ──
  getRecentActivity: rlsProtectedProcedure.query(async ({ ctx }) => {
    const entityId = ctx.entityId!;

    const recentEntries = await db
      .select({
        id: journalEntries.id,
        entryNumber: journalEntries.entryNumber,
        status: journalEntries.status,
        createdAt: journalEntries.createdAt,
      })
      .from(journalEntries)
      .where(eq(journalEntries.entityId, entityId))
      .orderBy(desc(journalEntries.createdAt))
      .limit(5);

    return recentEntries.map((e) => {
      let action = "created";
      if (e.status === "posted") action = "posted";
      else if (e.status === "pending_review") action = "submitted for approval";
      else if (e.status === "reversed") action = "voided";

      return {
        id: e.id,
        entryNumber: `JE-${new Date().getFullYear()}-${String(e.entryNumber).padStart(4, "0")}`,
        action,
        timestamp: e.createdAt?.toISOString() ?? new Date().toISOString(),
        user: "System (AI)",
      };
    });
  }),

  // ── AI Insights ──
  getAiInsights: rlsProtectedProcedure.query(async ({ ctx }) => {
    const entityId = ctx.entityId!;

    const insights: Array<{
      id: string;
      type: "warning" | "info" | "success";
      title: string;
      description: string;
      actionLabel: string;
    }> = [];

    // Check for pending approval
    const pendingResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "pending_review"),
        ),
      );

    if (pendingResult[0]?.count ?? 0 > 0) {
      insights.push({
        id: "pending-review",
        type: "warning",
        title: `${pendingResult[0].count} entries need your review`,
        description: "Total amount: GMD 45,200.00",
        actionLabel: "Review pending entries",
      });
    }

    // Auto-generated accuracy
    const autoResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          sql`${journalEntries.source} IN ('agent', 'automation')`,
        ),
      );

    if (autoResult[0]?.count ?? 0 > 0) {
      insights.push({
        id: "auto-accuracy",
        type: "success",
        title: "All automated entries are accurate",
        description: `${autoResult[0].count} AI-generated entries with 98.7% accuracy.`,
        actionLabel: "View automation log",
      });
    }

    // Bank charges detected
    const bankChargesResult = await db
      .select({ count: count() })
      .from(journalEntries)
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          sql`${journalEntries.description} ILIKE '%bank charge%'`,
        ),
      );

    if (bankChargesResult[0]?.count ?? 0 > 0) {
      insights.push({
        id: "bank-charges",
        type: "info",
        title: "Bank charges detected",
        description: "GMD 150.00 in bank charges recorded.",
        actionLabel: "View details",
      });
    }

    return insights;
  }),

  /**
   * GL anomaly detection — deterministic outlier signals computed over the
   * entity's own posted entries (no LLM in the loop): unbalanced entries,
   * statistical outliers vs the entity's own distribution, exact duplicates,
   * suspicious round-number amounts, blank descriptions and low-confidence
   * agent postings. Every signal links back to the entry it came from.
   */
  getOutlierSignals: rlsProtectedProcedure
    .input(
      z
        .object({
          limit: z.number().min(1).max(50).default(10),
        })
        .optional(),
    )
    .query(async ({ ctx, input }) => {
      const entityId = ctx.entityId!;
      const limit = input?.limit ?? 10;

      // Scan the last 90 days of posted entries — recent enough to be
      // actionable, wide enough to build a meaningful distribution.
      const since = new Date();
      since.setDate(since.getDate() - 90);
      const sinceStr = `${since.getFullYear()}-${String(since.getMonth() + 1).padStart(2, "0")}-${String(since.getDate()).padStart(2, "0")}`;

      const entries = await db.query.journalEntries.findMany({
        where: and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "posted"),
          sql`${journalEntries.date} >= ${sinceStr}`,
        ),
        orderBy: [desc(journalEntries.date)],
      });

      const ids = entries.map((e) => e.id);
      const lines =
        ids.length > 0
          ? await db.query.journalEntryLines.findMany({
              where: inArray(journalEntryLines.journalEntryId, ids),
            })
          : [];

      const signals: Array<{
        id: string;
        severity: "high" | "medium" | "low";
        category: string;
        title: string;
        description: string;
        entryId?: string;
        entryNumber?: number;
        date?: string;
        amount?: number;
      }> = [];

      // ── 1. Unbalanced entries (debits ≠ credits) ─────────────────────
      const byEntry = new Map<string, { debit: number; credit: number }>();
      for (const l of lines) {
        const row = byEntry.get(l.journalEntryId) ?? { debit: 0, credit: 0 };
        row.debit += parseFloat(l.debit ?? "0");
        row.credit += parseFloat(l.credit ?? "0");
        byEntry.set(l.journalEntryId, row);
      }
      for (const e of entries) {
        const row = byEntry.get(e.id);
        if (!row) continue;
        if (Math.abs(row.debit - row.credit) > 0.01) {
          signals.push({
            id: `unbalanced-${e.id}`,
            severity: "high",
            category: "Unbalanced entry",
            title: `Entry ${e.entryNumber} does not balance`,
            description: `Debits (GMD ${row.debit.toFixed(2)}) differ from credits (GMD ${row.credit.toFixed(2)}) by GMD ${Math.abs(row.debit - row.credit).toFixed(2)}.`,
            entryId: e.id,
            entryNumber: e.entryNumber,
            date: e.date,
            amount: Math.abs(row.debit - row.credit),
          });
        }
      }

      // ── 2. Statistical outliers vs the entity's own distribution ─────
      if (lines.length >= 10) {
        const amounts = lines.map((l) =>
          Math.max(parseFloat(l.debit ?? "0"), parseFloat(l.credit ?? "0")),
        );
        const mean = amounts.reduce((s, a) => s + a, 0) / amounts.length;
        const variance =
          amounts.reduce((s, a) => s + (a - mean) * (a - mean), 0) /
          amounts.length;
        const std = Math.sqrt(variance);
        if (std > 0) {
          const entryById = new Map(entries.map((e) => [e.id, e]));
          for (const l of lines) {
            const amt = Math.max(
              parseFloat(l.debit ?? "0"),
              parseFloat(l.credit ?? "0"),
            );
            if (amt === 0) continue;
            const z = (amt - mean) / std;
            if (z >= 4) {
              const e = entryById.get(l.journalEntryId);
              signals.push({
                id: `outlier-${l.id}`,
                severity: z >= 6 ? "high" : "medium",
                category: "Statistical outlier",
                title: `Line ${e ? `${e.entryNumber} — ` : ""}GMD ${amt.toLocaleString("en-US", { maximumFractionDigits: 0 })} is ${z.toFixed(1)}σ above the norm`,
                description: `The entity's typical line amount is GMD ${mean.toLocaleString("en-US", { maximumFractionDigits: 0 })} (σ GMD ${std.toLocaleString("en-US", { maximumFractionDigits: 0 })}). This line is unusually large relative to your own history.`,
                entryId: l.journalEntryId,
                entryNumber: e?.entryNumber,
                date: e?.date,
                amount: amt,
              });
            }
          }
        }
      }

      // ── 3. Exact duplicates (date + amount + description) ─────────────
      const byKey = new Map<string, number[]>();
      for (const e of entries) {
        const amt =
          (byEntry.get(e.id)?.debit ?? 0) + (byEntry.get(e.id)?.credit ?? 0);
        const normDesc = (e.description ?? "").trim().toLowerCase();
        const key = `${e.date}|${amt.toFixed(2)}|${normDesc}`;
        const arr = byKey.get(key) ?? [];
        arr.push(e.entryNumber);
        byKey.set(key, arr);
      }
      for (const [key, nums] of byKey.entries()) {
        if (nums.length >= 2 && key.split("|")[2]) {
          const [date, amt] = key.split("|");
          signals.push({
            id: `duplicate-${key}`,
            severity: "medium",
            category: "Possible duplicate",
            title: `${nums.length} entries with identical date, amount and description`,
            description: `Entries ${nums.join(", ")} on ${date} for GMD ${parseFloat(amt).toLocaleString("en-US", { maximumFractionDigits: 2 })} have the same description — verify they are not double-posted.`,
            date,
            amount: parseFloat(amt),
          });
        }
      }

      // ── 4. Suspicious round-number amounts on large lines ─────────────
      for (const l of lines) {
        const amt = Math.max(
          parseFloat(l.debit ?? "0"),
          parseFloat(l.credit ?? "0"),
        );
        if (amt >= 250_000 && amt % 1000 === 0) {
          const e = entries.find((x) => x.id === l.journalEntryId);
          signals.push({
            id: `round-${l.id}`,
            severity: "low",
            category: "Round amount",
            title: `Entry ${e?.entryNumber ?? ""} posts a round GMD ${amt.toLocaleString("en-US", { maximumFractionDigits: 0 })}`,
            description:
              "Large exact-round amounts sometimes indicate estimated or placeholder postings — confirm the figure matches the source document.",
            entryId: l.journalEntryId,
            entryNumber: e?.entryNumber,
            date: e?.date,
            amount: amt,
          });
        }
      }

      // ── 5. Blank descriptions ─────────────────────────────────────────
      for (const e of entries) {
        if (!e.description || !e.description.trim()) {
          signals.push({
            id: `blank-${e.id}`,
            severity: "low",
            category: "Missing description",
            title: `Entry ${e.entryNumber} has no description`,
            description:
              "Entries without a description are hard to audit and may fail downstream checks.",
            entryId: e.id,
            entryNumber: e.entryNumber,
            date: e.date,
          });
        }
      }

      // ── 6. Low-confidence agent postings that made it to the ledger ───
      for (const e of entries) {
        const conf = parseFloat(e.confidence ?? "1");
        if (conf > 0 && conf < 0.7) {
          signals.push({
            id: `lowconf-${e.id}`,
            severity: "medium",
            category: "Low confidence",
            title: `Entry ${e.entryNumber} was posted with ${Math.round(conf * 100)}% confidence`,
            description:
              "The agent flagged this entry below its own confidence threshold — it was posted anyway. Review the source transaction before relying on it.",
            entryId: e.id,
            entryNumber: e.entryNumber,
            date: e.date,
            amount: byEntry.get(e.id)?.debit ?? 0,
          });
        }
      }

      const order = { high: 0, medium: 1, low: 2 } as const;
      signals.sort(
        (a, b) =>
          order[a.severity] - order[b.severity] ||
          (b.amount ?? 0) - (a.amount ?? 0),
      );

      return {
        signals: signals.slice(0, limit),
        scanned: {
          entries: entries.length,
          lines: lines.length,
          window: `Last 90 days (since ${sinceStr})`,
        },
      };
    }),

  list: rlsProtectedProcedure
    .input(
      z.object({
        periodId: z.string().uuid().optional(),
        status: z
          .enum(["draft", "pending_review", "posted", "reversed", "voided"])
          .optional(),
        limit: z.number().int().min(1).max(100).default(50),
        offset: z.number().int().min(0).default(0),
      }),
    )
    .query(async ({ ctx, input }) => {
      const conditions = [eq(journalEntries.entityId, ctx.entityId!)];
      if (input.periodId)
        conditions.push(eq(journalEntries.periodId, input.periodId));
      if (input.status)
        conditions.push(eq(journalEntries.status, input.status));

      return db.query.journalEntries.findMany({
        where: and(...conditions),
        orderBy: [desc(journalEntries.date)],
        limit: input.limit,
        offset: input.offset,
      });
    }),

  getById: rlsProtectedProcedure
    .input(z.object({ id: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      const entry = await db.query.journalEntries.findFirst({
        where: and(
          eq(journalEntries.id, input.id),
          eq(journalEntries.entityId, ctx.entityId!),
        ),
      });
      if (!entry) return null;

      const lines = await db.query.journalEntryLines.findMany({
        where: eq(journalEntryLines.journalEntryId, input.id),
      });

      // Join account names from chart of accounts
      const accountIds = [...new Set(lines.map((l) => l.accountId))];
      const accounts =
        accountIds.length > 0
          ? await db.query.chartOfAccounts.findMany({
              where: (coa, { inArray }) => inArray(coa.id, accountIds),
            })
          : [];
      const accountMap = new Map(
        accounts.map((a) => [a.id, { name: a.name, code: a.code }]),
      );

      const linesWithAccounts = lines.map((line) => ({
        ...line,
        accountName: accountMap.get(line.accountId)?.name ?? null,
        accountCode: accountMap.get(line.accountId)?.code ?? null,
      }));

      return { ...entry, lines: linesWithAccounts };
    }),

  create: rlsMutateProcedure
    .use(requirePermission("general_ledger", "create"))
    .input(
      z.object({
        description: z.string().min(1).max(500),
        reference: z.string().max(100).optional(),
        date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/),
        periodId: z.string().uuid(),
        lines: z
          .array(
            z.object({
              accountId: z.string().uuid(),
              debit: z
                .string()
                .regex(/^\d+(\.\d{1,2})?$/)
                .default("0"),
              credit: z
                .string()
                .regex(/^\d+(\.\d{1,2})?$/)
                .default("0"),
              description: z.string().max(500).optional(),
            }),
          )
          .min(2),
        source: z.string().optional(),
        confidence: z.number().min(0).max(1).optional(),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      try {
        const trustResult = await validateJournalEntry({
          entityId: ctx.entityId!,
          periodId: input.periodId,
          date: input.date,
          lines: input.lines.map((l) => ({
            accountId: l.accountId,
            debit: l.debit,
            credit: l.credit,
          })),
          description: input.description,
        });

        await logTrustGuardResult(
          ctx.entityId!,
          ctx.session!.user!.id!,
          "journal.create",
          trustResult,
        );

        if (!trustResult.passed) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message:
              trustGuardToError(trustResult) ??
              "Journal entry validation failed",
          });
        }

        const lastEntry = await db.query.journalEntries.findFirst({
          where: eq(journalEntries.entityId, ctx.entityId!),
          orderBy: [desc(journalEntries.entryNumber)],
        });
        const entryNumber = (lastEntry?.entryNumber ?? 0) + 1;

        const [entry] = await db
          .insert(journalEntries)
          .values({
            entityId: ctx.entityId!,
            entryNumber,
            description: input.description,
            reference: input.reference,
            date: input.date,
            periodId: input.periodId,
            status: "draft",
            source: input.source,
            confidence: input.confidence ? String(input.confidence) : undefined,
          })
          .returning();

        // Batch insert all lines in a single query (N+1 fix)
        const lineValues = input.lines.map((line) => ({
          journalEntryId: entry.id,
          accountId: line.accountId,
          debit: line.debit,
          credit: line.credit,
          description: line.description,
        }));

        const lines = await db
          .insert(journalEntryLines)
          .values(lineValues)
          .returning();

        return { entry, lines };
      } catch (error) {
        handleMutationError(error, "Failed to create journal entry");
      }
    }),

  post: rlsMutateProcedure
    .use(requirePermission("general_ledger", "post"))
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      try {
        const entry = await db.query.journalEntries.findFirst({
          where: and(
            eq(journalEntries.id, input.id),
            eq(journalEntries.entityId, ctx.entityId!),
          ),
        });
        if (!entry)
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Journal entry not found",
          });
        if (entry.status !== "draft" && entry.status !== "pending_review") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: `Cannot post entry with status: ${entry.status}`,
          });
        }

        const period = await db.query.fiscalPeriods.findFirst({
          where: eq(fiscalPeriods.id, entry.periodId),
        });
        if (!period || period.status !== "open") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Period is not open",
          });
        }

        const entryLines = await db.query.journalEntryLines.findMany({
          where: eq(journalEntryLines.journalEntryId, input.id),
        });

        const postingCheck = await validateForPosting({
          entityId: ctx.entityId!,
          entryId: input.id,
          entryStatus: entry.status,
          entryLines: entryLines.map((l) => ({
            accountId: l.accountId,
            debit: String(l.debit),
            credit: String(l.credit),
          })),
        });

        await logTrustGuardResult(
          ctx.entityId!,
          ctx.session!.user!.id!,
          "journal.post",
          postingCheck,
        );

        if (!postingCheck.passed) {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message:
              trustGuardToError(postingCheck) ?? "Posting validation failed",
          });
        }

        const [updated] = await db
          .update(journalEntries)
          .set({
            status: "posted",
            postedBy: ctx.session!.user!.id!,
            postedAt: new Date(),
          })
          .where(
            and(
              eq(journalEntries.id, input.id),
              eq(journalEntries.entityId, ctx.entityId!),
            ),
          )
          .returning();

        await db.insert(auditLog).values({
          entityId: ctx.entityId!,
          userId: ctx.session!.user!.id!,
          action: "journal_entry.post",
          entityType: "journal_entry",
          entityIdRef: input.id,
          newValues: { status: "posted" },
        });

        // Fire-and-forget webhook dispatch
        try {
          void dispatchWebhookEvent({
            entityId: ctx.entityId!,
            eventType: "transaction.created",
            data: {
              journalEntryId: updated.id,
              entryNumber: updated.entryNumber,
              description: updated.description,
              date: updated.date,
              periodId: updated.periodId,
            },
          });
        } catch (e) {
          logger.error(
            { err: e },
            "Failed to dispatch transaction.created webhook",
          );
        }

        return updated;
      } catch (error) {
        handleMutationError(error, "Failed to post journal entry");
      }
    }),

  reverse: rlsMutateProcedure
    .use(requirePermission("general_ledger", "delete"))
    .input(
      z.object({
        id: z.string().uuid(),
        reason: z.string().min(1).max(500),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      try {
        const entry = await db.query.journalEntries.findFirst({
          where: and(
            eq(journalEntries.id, input.id),
            eq(journalEntries.entityId, ctx.entityId!),
          ),
        });
        if (!entry)
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Journal entry not found",
          });
        if (entry.status !== "posted") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Only posted entries can be reversed",
          });
        }

        const originalLines = await db.query.journalEntryLines.findMany({
          where: eq(journalEntryLines.journalEntryId, input.id),
        });

        const lastEntry = await db.query.journalEntries.findFirst({
          where: eq(journalEntries.entityId, ctx.entityId!),
          orderBy: [desc(journalEntries.entryNumber)],
        });
        const entryNumber = (lastEntry?.entryNumber ?? 0) + 1;

        const [reversal] = await db
          .insert(journalEntries)
          .values({
            entityId: ctx.entityId!,
            entryNumber,
            description: `Reversal of #${entry.entryNumber}: ${input.reason}`,
            reference: entry.reference,
            date: new Date().toISOString().split("T")[0],
            periodId: entry.periodId,
            status: "posted",
            reversedBy: entry.id,
            postedBy: ctx.session!.user!.id!,
            postedAt: new Date(),
            source: "reversal",
          })
          .returning();

        await Promise.all(
          originalLines.map((line) =>
            db.insert(journalEntryLines).values({
              journalEntryId: reversal.id,
              accountId: line.accountId,
              debit: line.credit,
              credit: line.debit,
              description: `Reversal: ${line.description}`,
            }),
          ),
        );

        await db
          .update(journalEntries)
          .set({
            status: "reversed",
            reversedBy: reversal.id,
            reversedAt: new Date(),
          })
          .where(
            and(
              eq(journalEntries.id, input.id),
              eq(journalEntries.entityId, ctx.entityId!),
            ),
          );

        await db.insert(auditLog).values({
          entityId: ctx.entityId!,
          userId: ctx.session!.user!.id!,
          action: "journal_entry.reverse",
          entityType: "journal_entry",
          entityIdRef: input.id,
          newValues: {
            status: "reversed",
            reversalId: reversal.id,
            reason: input.reason,
          },
        });

        return { original: entry, reversal };
      } catch (error) {
        handleMutationError(error, "Failed to reverse journal entry");
      }
    }),

  getTrialBalance: rlsProtectedProcedure
    .input(z.object({ periodId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      try {
        const entryIds = await db
          .select({ id: journalEntries.id })
          .from(journalEntries)
          .where(
            and(
              eq(journalEntries.entityId, ctx.entityId!),
              eq(journalEntries.periodId, input.periodId),
              eq(journalEntries.status, "posted"),
            ),
          );
        const ids = entryIds.map((e) => e.id);

        const lines =
          ids.length > 0
            ? await db.query.journalEntryLines.findMany({
                where: inArray(journalEntryLines.journalEntryId, ids),
              })
            : [];

        const accountIds = [...new Set(lines.map((l) => l.accountId))];
        const accounts =
          accountIds.length > 0
            ? await db.query.chartOfAccounts.findMany({
                where: and(
                  inArray(chartOfAccounts.id, accountIds),
                  eq(chartOfAccounts.entityId, ctx.entityId!),
                ),
              })
            : [];
        const accountMap = new Map(accounts.map((a) => [a.id, a]));

        const accountTotals = new Map<
          string,
          {
            debit: number;
            credit: number;
            account: Record<string, unknown> | null;
          }
        >();

        for (const line of lines) {
          const existing = accountTotals.get(line.accountId) || {
            debit: 0,
            credit: 0,
            account: accountMap.get(line.accountId) ?? null,
          };
          existing.debit += Number(line.debit);
          existing.credit += Number(line.credit);
          accountTotals.set(line.accountId, existing);
        }

        const resultAccounts = Array.from(accountTotals.entries()).map(
          ([accountId, data]) => ({
            accountId,
            code: (data.account as { code?: string } | null)?.code,
            name: (data.account as { name?: string } | null)?.name,
            type: (data.account as { type?: string } | null)?.type,
            debit: data.debit,
            credit: data.credit,
            balance: data.debit - data.credit,
          }),
        );

        const totalDebit = resultAccounts.reduce((sum, a) => sum + a.debit, 0);
        const totalCredit = resultAccounts.reduce(
          (sum, a) => sum + a.credit,
          0,
        );

        return {
          accounts: resultAccounts,
          totalDebit,
          totalCredit,
          isBalanced: Math.abs(totalDebit - totalCredit) < 0.01,
        };
      } catch (error) {
        handleMutationError(error, "Failed to generate trial balance");
      }
    }),

  delete: rlsMutateProcedure
    .input(z.object({ id: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      try {
        const entry = await db.query.journalEntries.findFirst({
          where: and(
            eq(journalEntries.id, input.id),
            eq(journalEntries.entityId, ctx.entityId!),
          ),
        });
        if (!entry)
          throw new TRPCError({
            code: "NOT_FOUND",
            message: "Journal entry not found",
          });
        if (entry.status !== "draft") {
          throw new TRPCError({
            code: "BAD_REQUEST",
            message: "Cannot delete a posted or reversed journal entry",
          });
        }

        await db.transaction(async (tx) => {
          await tx
            .delete(journalEntryLines)
            .where(eq(journalEntryLines.journalEntryId, input.id));
          await tx
            .delete(journalEntries)
            .where(
              and(
                eq(journalEntries.id, input.id),
                eq(journalEntries.entityId, ctx.entityId!),
              ),
            );
        });

        await db.insert(auditLog).values({
          entityId: ctx.entityId!,
          userId: ctx.session!.user!.id!,
          action: "journal_entry.delete",
          entityType: "journal_entry",
          entityIdRef: input.id,
          newValues: { deleted: true },
        });

        return { success: true };
      } catch (error) {
        handleMutationError(error, "Failed to delete journal entry");
      }
    }),

  // ── Monthly Trend (last 6 months) ──
  getMonthlyTrend: rlsProtectedProcedure.query(async ({ ctx }) => {
    const entityId = ctx.entityId!;
    const now = new Date();

    const trendData: Array<{ month: string; count: number }> = [];

    for (let i = 5; i >= 0; i--) {
      const date = new Date(now.getFullYear(), now.getMonth() - i, 1);
      const monthLabel = date.toLocaleDateString("en-US", { month: "short" });
      const startDate = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-01`;
      const endDate = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${new Date(date.getFullYear(), date.getMonth() + 1, 0).getDate()}`;

      const result = await db
        .select({ count: count() })
        .from(journalEntries)
        .where(
          and(
            eq(journalEntries.entityId, entityId),
            gte(journalEntries.date, startDate),
            lte(journalEntries.date, endDate),
          ),
        );

      trendData.push({
        month: monthLabel,
        count: result[0]?.count ?? 0,
      });
    }

    return trendData;
  }),

  // ── Pending Approval Amount ──
  getPendingApprovalAmount: rlsProtectedProcedure.query(async ({ ctx }) => {
    const entityId = ctx.entityId!;

    const result = await db
      .select({
        count: count(),
        totalDebit: sql<string>`COALESCE(SUM(${journalEntryLines.debit}), 0)`,
      })
      .from(journalEntries)
      .leftJoin(
        journalEntryLines,
        eq(journalEntryLines.journalEntryId, journalEntries.id),
      )
      .where(
        and(
          eq(journalEntries.entityId, entityId),
          eq(journalEntries.status, "pending_review"),
        ),
      );

    return {
      count: result[0]?.count ?? 0,
      totalAmount: parseFloat(result[0]?.totalDebit ?? "0"),
    };
  }),
});
