-- Legal Mechanisms: ToS acceptance tracking, owner notifications, Pro-tier review
--
-- NOTE (fresh-DB fix): ALL objects from this migration are canonically
-- created by 0015_conscious_namora (drizzle-generated):
--   * the four enum types (0015's value sets are the live ones — e.g.
--     agreement_status includes 'superseded', review_status 'in_review')
--   * legal_acceptances / owner_notifications / pro_tier_reviews tables +
--     their indexes
--   * their FK constraints
-- This file previously created older versions of the enums and tables
-- (IF NOT EXISTS / DO-block guarded), but 0015 hard-creates them later,
-- which fails on a fresh database. Production never executed this file
-- (retro-inserted below prod's __drizzle_migrations watermark), so it is
-- intentionally a no-op retained for journal continuity. RLS policies for
-- these tables live in 0043_rls_catchup.sql.
