-- §886 Partial indexes for hot states
-- Generated by drizzle-kit from schema edits in notifications.ts + agents.ts.
--
-- NOTE: drizzle-kit also emitted unrelated `ALTER COLUMN ... SET DATA TYPE
-- uuid` drift statements (review_items, workflows, automations, ...) because
-- the migrations snapshot lags the current schema. Those were REMOVED — type
-- conversions on production tables are a separate, deliberate migration, not
-- something to smuggle in with an index change.
--
-- §878 Partition-wise settings are server/database config, not migration
-- DDL (ALTER DATABASE name SET enable_partitionwise_join = on; + 
-- enable_partitionwise_aggregate = on;) — see DATABASE.md §partitioning.

CREATE INDEX "approvals_pending_idx" ON "approvals" USING btree ("entity_id","created_at") WHERE status = 'pending';--> statement-breakpoint
CREATE INDEX "notifications_unread_idx" ON "notifications" USING btree ("user_id","created_at") WHERE read = false;
