-- Generated by drizzle-kit (0040_majestic_gamora), then corrected: Postgres
-- cannot auto-cast timestamp → integer without a USING clause. The column has
-- never been written (all rows NULL), so `USING NULL::integer` is a safe
-- constant cast. Amendment documented in REBUILD_LOG.md Session 007.
ALTER TABLE "idempotency_keys" ALTER COLUMN "status_code" DROP DEFAULT;
ALTER TABLE "idempotency_keys" ALTER COLUMN "status_code" TYPE integer USING NULL::integer;
