"use client";

// ─── Document Generation Utilities ─────────────────────────────────────────
//
// Client-side generation of PDF, Excel, and Word documents from financial data.
// All generation happens in the browser — no server load, works offline.

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";
import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  HeadingLevel,
  BorderStyle,
  ShadingType,
  type TableRowProps,
} from "docx";
import { saveAs } from "file-saver";

// ─── Types ─────────────────────────────────────────────────────────────────

export type DocumentFormat = "pdf" | "excel" | "word";

export type ReportData = {
  title: string;
  subtitle?: string;
  entityName: string;
  currency: string;
  generatedAt: Date;
  sections: ReportSection[];
};

export type ReportSection = {
  heading: string;
  intro?: string;
  table?: {
    columns: string[];
    rows: Array<Array<string | number>>;
  };
  paragraphs?: string[];
  bullets?: string[];
  footer?: Array<{ label: string; value: string }>;
};

// ─── PDF Generation ────────────────────────────────────────────────────────

export async function generatePDF(data: ReportData): Promise<Blob> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Header
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, margin, y);
  y += 8;

  if (data.subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text(data.subtitle, margin, y);
    y += 6;
  }

  // Metadata line
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(
    `Generated by Xenboox AI · ${data.entityName} · ${data.currency} · ${data.generatedAt.toLocaleDateString()}`,
    margin,
    y,
  );
  y += 4;

  // Divider
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Sections
  for (const section of data.sections) {
    // Check if we need a new page
    if (y > 260) {
      doc.addPage();
      y = margin;
    }

    // Section heading
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(79, 70, 229); // Brand color
    doc.text(section.heading, margin, y);
    y += 7;

    // Intro
    if (section.intro) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      const introLines = doc.splitTextToSize(section.intro, contentWidth);
      doc.text(introLines, margin, y);
      y += introLines.length * 4 + 3;
    }

    // Paragraphs
    if (section.paragraphs) {
      for (const p of section.paragraphs) {
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(30);
        const lines = doc.splitTextToSize(p, contentWidth);
        doc.text(lines, margin, y);
        y += lines.length * 4 + 2;
      }
    }

    // Bullets
    if (section.bullets) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(30);
      for (const b of section.bullets) {
        const lines = doc.splitTextToSize(`• ${b}`, contentWidth - 5);
        doc.text(lines, margin + 5, y);
        y += lines.length * 4 + 1;
      }
      y += 2;
    }

    // Table
    if (section.table) {
      autoTable(doc, {
        startY: y,
        head: [section.table.columns],
        body: section.table.rows.map((r) => r.map(String)),
        margin: { left: margin, right: margin },
        styles: { fontSize: 8, cellPadding: 3 },
        headStyles: {
          fillColor: [79, 70, 229],
          textColor: 255,
          fontStyle: "bold",
        },
        alternateRowStyles: { fillColor: [248, 250, 252] },
      });
      y =
        (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable
          .finalY + 5;
    }

    // Footer totals
    if (section.footer) {
      for (const f of section.footer) {
        doc.setFontSize(9);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100);
        doc.text(f.label, margin, y);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30);
        doc.text(f.value, pageWidth - margin, y, { align: "right" });
        y += 5;
      }
      y += 5;
    }
  }

  // Page footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `Xenboox · ${data.entityName} · Page ${i} of ${pageCount}`,
      margin,
      doc.internal.pageSize.getHeight() - 10,
    );
  }

  return doc.output("blob");
}

// ─── Excel Generation ──────────────────────────────────────────────────────

export async function generateExcel(data: ReportData): Promise<Blob> {
  const wb = XLSX.utils.book_new();

  // Summary sheet
  const summaryData: Array<Array<string | number>> = [
    [data.title],
    [data.subtitle || ""],
    [`Generated: ${data.generatedAt.toLocaleDateString()}`],
    [`Entity: ${data.entityName}`],
    [`Currency: ${data.currency}`],
    [],
  ];

  for (const section of data.sections) {
    summaryData.push([section.heading]);
    if (section.table) {
      summaryData.push(section.table.columns);
      summaryData.push(...section.table.rows);
    }
    if (section.footer) {
      summaryData.push([]);
      for (const f of section.footer) {
        summaryData.push([f.label, f.value]);
      }
    }
    summaryData.push([]);
  }

  const ws = XLSX.utils.aoa_to_sheet(summaryData);

  // Set column widths
  if (data.sections[0]?.table) {
    const colCount = data.sections[0].table.columns.length;
    ws["!cols"] = Array.from({ length: colCount }, (_, i) => ({
      wch: i === 0 ? 35 : 18,
    }));
  }

  XLSX.utils.book_append_sheet(wb, ws, "Summary");

  // Individual section sheets
  for (const section of data.sections) {
    if (!section.table) continue;

    const sheetData: Array<Array<string | number>> = [];
    if (section.intro) sheetData.push([section.intro]);
    sheetData.push(section.table.columns);
    sheetData.push(...section.table.rows);
    if (section.footer) {
      sheetData.push([]);
      for (const f of section.footer) {
        sheetData.push([f.label, f.value]);
      }
    }

    const sectionWs = XLSX.utils.aoa_to_sheet(sheetData);
    const sheetName = section.heading.slice(0, 31).replace(/[\/\\?*[\]]/g, "");
    XLSX.utils.book_append_sheet(wb, sectionWs, sheetName);
  }

  // Generate blob
  const excelBuffer = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  return new Blob([excelBuffer], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
}

// ─── Word Generation ───────────────────────────────────────────────────────

export async function generateWord(data: ReportData): Promise<Blob> {
  const children: Paragraph[] = [];

  // Title
  children.push(
    new Paragraph({
      text: data.title,
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 },
    }),
  );

  // Subtitle
  if (data.subtitle) {
    children.push(
      new Paragraph({
        text: data.subtitle,
        heading: HeadingLevel.HEADING_2,
        spacing: { after: 100 },
        color: "64748b",
      }),
    );
  }

  // Metadata
  children.push(
    new Paragraph({
      text: `Generated by Xenboox AI · ${data.entityName} · ${data.currency} · ${data.generatedAt.toLocaleDateString()}`,
      spacing: { after: 200 },
      color: "94a3b8",
    }),
  );

  // Divider
  children.push(
    new Paragraph({
      spacing: { after: 200 },
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "e2e8f0" },
      },
    }),
  );

  // Sections
  for (const section of data.sections) {
    // Section heading
    children.push(
      new Paragraph({
        text: section.heading,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 300, after: 150 },
        color: "4f46e5",
      }),
    );

    // Intro
    if (section.intro) {
      children.push(
        new Paragraph({
          text: section.intro,
          spacing: { after: 150 },
          color: "64748b",
        }),
      );
    }

    // Paragraphs
    if (section.paragraphs) {
      for (const p of section.paragraphs) {
        children.push(
          new Paragraph({
            text: p,
            spacing: { after: 100 },
          }),
        );
      }
    }

    // Bullets
    if (section.bullets) {
      for (const b of section.bullets) {
        children.push(
          new Paragraph({
            text: b,
            bullet: { level: 0 },
            spacing: { after: 50 },
          }),
        );
      }
    }

    // Table
    if (section.table) {
      const tableRows: TableRow[] = [];

      // Header row
      tableRows.push(
        new TableRow({
          children: section.table.columns.map(
            (col) =>
              new TableCell({
                children: [new Paragraph({ text: col, bold: true })],
                shading: {
                  type: ShadingType.SOLID,
                  color: "4f46e5",
                  fill: "4f46e5",
                },
              }),
          ),
        }),
      );

      // Data rows
      for (const row of section.table.rows) {
        tableRows.push(
          new TableRow({
            children: row.map(
              (cell) =>
                new TableCell({
                  children: [new Paragraph({ text: String(cell) })],
                }),
            ),
          }),
        );
      }

      children.push(
        new Table({
          rows: tableRows,
          width: { size: 100, type: WidthType.PERCENTAGE },
        }),
      );

      children.push(new Paragraph({ spacing: { after: 200 } }));
    }

    // Footer totals
    if (section.footer) {
      for (const f of section.footer) {
        children.push(
          new Paragraph({
            children: [
              { text: `${f.label}: `, bold: false },
              { text: f.value, bold: true },
            ],
            spacing: { after: 50 },
          }),
        );
      }
    }
  }

  // Create document
  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
  });

  // Generate blob
  const buffer = await Packer.toBlob(doc);
  return buffer;
}

// ─── Download Helper ───────────────────────────────────────────────────────

export async function downloadDocument(
  data: ReportData,
  format: DocumentFormat,
): Promise<void> {
  let blob: Blob;
  let filename: string;
  let mimeType: string;

  const safeName = data.title.replace(/[^a-zA-Z0-9]/g, "_").slice(0, 50);
  const dateStr = data.generatedAt.toISOString().split("T")[0];

  switch (format) {
    case "pdf":
      blob = await generatePDF(data);
      filename = `${safeName}_${dateStr}.pdf`;
      mimeType = "application/pdf";
      break;
    case "excel":
      blob = await generateExcel(data);
      filename = `${safeName}_${dateStr}.xlsx`;
      mimeType =
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
      break;
    case "word":
      blob = await generateWord(data);
      filename = `${safeName}_${dateStr}.docx`;
      mimeType =
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
      break;
  }

  saveAs(blob, filename);
}
