"use client";

// ─── Professional PDF Generator ────────────────────────────────────────────
//
// Generates branded, professional PDF reports with:
// - Branded header with logo placeholder and company name
// - Professional color scheme matching the app
// - Proper typography and spacing
// - Page numbers and generation timestamp
// - Table styling with alternating rows
// - Footer totals with emphasis
// - Multi-page support with page breaks

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ReportData, ReportSection } from "./generate-documents";
import { BRAND } from "./report-templates";

type PDFDoc = jsPDF & { lastAutoTable?: { finalY: number } };

// ─── Colors ────────────────────────────────────────────────────────────────

const COLORS = {
  brand: { r: 79, g: 70, b: 229 }, // #4f46e5
  brandLight: { r: 238, g: 242, b: 255 }, // #eef2ff
  text: { r: 15, g: 23, b: 42 }, // #0f172a
  muted: { r: 100, g: 116, b: 139 }, // #64748b
  light: { r: 248, g: 250, b: 252 }, // #f8fafc
  border: { r: 226, g: 232, b: 240 }, // #e2e8f0
  success: { r: 16, g: 185, b: 129 }, // #10b981
  danger: { r: 239, g: 68, b: 68 }, // #ef4444
};

// ─── PDF Generation ────────────────────────────────────────────────────────

export async function generateProfessionalPDF(data: ReportData): Promise<Blob> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  }) as PDFDoc;

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // ── Header ────────────────────────────────────────────────────────────
  y = renderHeader(doc, data, margin, contentWidth, y);

  // ── Sections ──────────────────────────────────────────────────────────
  for (const section of data.sections) {
    // Check if we need a new page (reserve space for footer)
    if (y > pageHeight - 35) {
      renderFooter(doc, data, margin, contentWidth, pageWidth, pageHeight);
      doc.addPage();
      y = margin;
    }

    y = renderSection(doc, section, margin, contentWidth, y, pageHeight, data);
  }

  // ── Final footer ──────────────────────────────────────────────────────
  renderFooter(doc, data, margin, contentWidth, pageWidth, pageHeight);

  return doc.output("blob");
}

// ─── Header Renderer ───────────────────────────────────────────────────────

function renderHeader(
  doc: PDFDoc,
  data: ReportData,
  margin: number,
  contentWidth: number,
  y: number,
): number {
  // Brand bar
  doc.setFillColor(COLORS.brand.r, COLORS.brand.g, COLORS.brand.b);
  doc.rect(0, 0, doc.internal.pageSize.getWidth(), 3, "F");

  y = 12;

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
  doc.text(data.title, margin, y);
  y += 7;

  // Subtitle
  if (data.subtitle) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.muted.r, COLORS.muted.g, COLORS.muted.b);
    doc.text(data.subtitle, margin, y);
    y += 5;
  }

  // Metadata line
  doc.setFontSize(8);
  doc.setTextColor(COLORS.muted.r, COLORS.muted.g, COLORS.muted.b);
  const metaText = `Generated by ${BRAND.name} AI · ${data.entityName} · ${data.currency} · ${data.generatedAt.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`;
  doc.text(metaText, margin, y);
  y += 3;

  // Divider
  doc.setDrawColor(COLORS.border.r, COLORS.border.g, COLORS.border.b);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentWidth, y);
  y += 6;

  return y;
}

// ─── Section Renderer ──────────────────────────────────────────────────────

function renderSection(
  doc: PDFDoc,
  section: ReportSection,
  margin: number,
  contentWidth: number,
  y: number,
  pageHeight: number,
  data: ReportData,
): number {
  // Section heading
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(COLORS.brand.r, COLORS.brand.g, COLORS.brand.b);
  doc.text(section.heading, margin, y);
  y += 6;

  // Intro
  if (section.intro) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(COLORS.muted.r, COLORS.muted.g, COLORS.muted.b);
    const introLines = doc.splitTextToSize(section.intro, contentWidth);
    doc.text(introLines, margin, y);
    y += introLines.length * 4 + 3;
  }

  // Paragraphs
  if (section.paragraphs) {
    for (const p of section.paragraphs) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
      const lines = doc.splitTextToSize(p, contentWidth);
      doc.text(lines, margin, y);
      y += lines.length * 4 + 2;
    }
  }

  // Bullets
  if (section.bullets) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
    for (const b of section.bullets) {
      // Check page break
      if (y > pageHeight - 35) {
        renderFooter(
          doc,
          data,
          margin,
          contentWidth,
          doc.internal.pageSize.getWidth(),
          pageHeight,
        );
        doc.addPage();
        y = margin;
      }
      doc.text("•", margin + 2, y);
      const lines = doc.splitTextToSize(b, contentWidth - 8);
      doc.text(lines, margin + 7, y);
      y += lines.length * 4 + 1;
    }
    y += 2;
  }

  // Table
  if (section.table && section.table.rows.length > 0) {
    autoTable(doc, {
      startY: y,
      head: [section.table.columns],
      body: section.table.rows.map((r) => r.map(String)),
      margin: { left: margin, right: margin },
      styles: {
        fontSize: 8,
        cellPadding: 3,
        textColor: [COLORS.text.r, COLORS.text.g, COLORS.text.b],
        lineColor: [COLORS.border.r, COLORS.border.g, COLORS.border.b],
        lineWidth: 0.1,
      },
      headStyles: {
        fillColor: [COLORS.brand.r, COLORS.brand.g, COLORS.brand.b],
        textColor: [255, 255, 255],
        fontStyle: "bold",
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [COLORS.light.r, COLORS.light.g, COLORS.light.b],
      },
      didParseCell: (hookData) => {
        // Right-align numeric columns (heuristic: contains currency symbol or number)
        if (hookData.section === "body") {
          const cellValue = String(hookData.cell.raw);
          if (/^[\d,.\s]/.test(cellValue) || cellValue.startsWith("$")) {
            hookData.cell.styles.halign = "right";
          }
        }
      },
    });
    y = (doc.lastAutoTable?.finalY ?? y) + 5;
  }

  // Footer totals
  if (section.footer) {
    // Check page break
    if (y > pageHeight - 35) {
      renderFooter(
        doc,
        data,
        margin,
        contentWidth,
        doc.internal.pageSize.getWidth(),
        pageHeight,
      );
      doc.addPage();
      y = margin;
    }

    // Totals box
    doc.setFillColor(
      COLORS.brandLight.r,
      COLORS.brandLight.g,
      COLORS.brandLight.b,
    );
    const boxHeight = section.footer.length * 5 + 4;
    doc.roundedRect(margin, y - 2, contentWidth, boxHeight, 2, 2, "F");

    y += 2;
    for (const f of section.footer) {
      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(COLORS.muted.r, COLORS.muted.g, COLORS.muted.b);
      doc.text(f.label, margin + 4, y);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(COLORS.text.r, COLORS.text.g, COLORS.text.b);
      doc.text(f.value, margin + contentWidth - 4, y, { align: "right" });
      y += 5;
    }
    y += 4;
  }

  return y;
}

// ─── Footer Renderer ───────────────────────────────────────────────────────

function renderFooter(
  doc: PDFDoc,
  data: ReportData,
  margin: number,
  contentWidth: number,
  pageWidth: number,
  pageHeight: number,
): void {
  const pageCount = doc.getNumberOfPages();

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);

    // Footer line
    doc.setDrawColor(COLORS.border.r, COLORS.border.g, COLORS.border.b);
    doc.setLineWidth(0.3);
    doc.line(margin, pageHeight - 18, margin + contentWidth, pageHeight - 18);

    // Footer text
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(COLORS.muted.r, COLORS.muted.g, COLORS.muted.b);
    doc.text(`${BRAND.name} · ${BRAND.tagline}`, margin, pageHeight - 14);
    doc.text(
      `${data.entityName} · Page ${i} of ${pageCount}`,
      pageWidth - margin,
      pageHeight - 14,
      { align: "right" },
    );

    // Brand bar at bottom
    doc.setFillColor(COLORS.brand.r, COLORS.brand.g, COLORS.brand.b);
    doc.rect(0, pageHeight - 3, pageWidth, 3, "F");
  }
}
