"use client";

// ─── Professional Word Generator ───────────────────────────────────────────
//
// Generates professional Word documents with:
// - Branded title page
// - Proper heading hierarchy
// - Tables with colored headers
// - Bullet lists with proper indentation
// - Professional spacing and typography

import {
  Document,
  Packer,
  Paragraph,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  HeadingLevel,
  BorderStyle,
  ShadingType,
  TabStopType,
  TabStopPosition,
  type ParagraphChildren,
} from "docx";
import type { ReportData, ReportSection } from "./generate-documents";

// ─── Brand Config ──────────────────────────────────────────────────────────

const BRAND = {
  name: "Xenboox",
  color: "4F46E5",
  tagline: "AI-Native Accounting Platform",
};

// ─── Word Generation ───────────────────────────────────────────────────────

export async function generateWord(data: ReportData): Promise<Blob> {
  const children: Paragraph[] = [];

  // ── Title Page ───────────────────────────────────────────────────────
  children.push(
    new Paragraph({ spacing: { before: 2400 } }),
    new Paragraph({
      text: data.title,
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
  );

  if (data.subtitle) {
    children.push(
      new Paragraph({
        text: data.subtitle,
        heading: HeadingLevel.SUBTITLE,
        alignment: AlignmentType.CENTER,
        color: "64748b",
        spacing: { after: 200 },
      }),
    );
  }

  children.push(
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        {
          text: `Generated by ${BRAND.name} AI`,
          color: "94a3b8",
          size: 20,
        },
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
      children: [
        {
          text: data.generatedAt.toLocaleDateString("en-US", {
            year: "numeric",
            month: "long",
            day: "numeric",
          }),
          color: "94a3b8",
          size: 20,
        },
      ],
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
      children: [
        {
          text: `${data.entityName} · ${data.currency}`,
          color: "94a3b8",
          size: 20,
        },
      ],
    }),
    // Page break
    new Paragraph({ spacing: { after: 200 }, pageBreakBefore: true }),
  );

  // ── Sections ─────────────────────────────────────────────────────────
  for (const section of data.sections) {
    // Section heading
    children.push(
      new Paragraph({
        text: section.heading,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 400, after: 200 },
        color: BRAND.color,
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 1, color: "e2e8f0" },
        },
      }),
    );

    // Intro
    if (section.intro) {
      children.push(
        new Paragraph({
          text: section.intro,
          spacing: { after: 200 },
          color: "64748b",
          italics: true,
        }),
      );
    }

    // Paragraphs
    if (section.paragraphs) {
      for (const p of section.paragraphs) {
        children.push(
          new Paragraph({
            text: p,
            spacing: { after: 150 },
            size: 22, // 11pt
          }),
        );
      }
    }

    // Bullets
    if (section.bullets) {
      for (const b of section.bullets) {
        children.push(
          new Paragraph({
            text: b,
            bullet: { level: 0 },
            spacing: { after: 80 },
            size: 22,
          }),
        );
      }
    }

    // Table
    if (section.table && section.table.rows.length > 0) {
      const tableRows: TableRow[] = [];

      // Header row
      tableRows.push(
        new TableRow({
          children: section.table.columns.map(
            (col) =>
              new TableCell({
                children: [
                  new Paragraph({
                    children: [
                      { text: col, bold: true, color: "FFFFFF", size: 20 },
                    ],
                  }),
                ],
                shading: {
                  type: ShadingType.SOLID,
                  color: BRAND.color,
                  fill: BRAND.color,
                },
                width: {
                  size: 100 / section.table!.columns.length,
                  type: WidthType.PERCENTAGE,
                },
              }),
          ),
        }),
      );

      // Data rows with alternating shading
      for (let i = 0; i < section.table.rows.length; i++) {
        const row = section.table.rows[i];
        const isEven = i % 2 === 0;

        tableRows.push(
          new TableRow({
            children: row.map(
              (cell) =>
                new TableCell({
                  children: [
                    new Paragraph({
                      children: [{ text: String(cell), size: 20 }],
                    }),
                  ],
                  shading: isEven
                    ? undefined
                    : {
                        type: ShadingType.SOLID,
                        color: "f8fafc",
                        fill: "f8fafc",
                      },
                  width: {
                    size: 100 / section.table!.columns.length,
                    type: WidthType.PERCENTAGE,
                  },
                }),
            ),
          }),
        );
      }

      children.push(
        new Table({
          rows: tableRows,
          width: { size: 100, type: WidthType.PERCENTAGE },
        }),
      );

      children.push(new Paragraph({ spacing: { after: 200 } }));
    }

    // Footer totals
    if (section.footer) {
      // Totals box
      children.push(
        new Paragraph({
          spacing: { before: 100, after: 50 },
          border: {
            top: { style: BorderStyle.SINGLE, size: 1, color: "e2e8f0" },
          },
        }),
      );

      for (const f of section.footer) {
        children.push(
          new Paragraph({
            spacing: { after: 50 },
            children: [
              {
                text: `${f.label}: `,
                color: "64748b",
                size: 22,
              },
              {
                text: f.value,
                bold: true,
                size: 22,
              },
            ],
          }),
        );
      }
    }
  }

  // ── Create Document ──────────────────────────────────────────────────
  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: {
              top: 1440, // 1 inch
              right: 1440,
              bottom: 1440,
              left: 1440,
            },
          },
        },
        children,
      },
    ],
    styles: {
      default: {
        document: {
          run: {
            font: "Calibri",
            size: 22, // 11pt
          },
        },
      },
    },
  });

  return Packer.toBlob(doc);
}
